# PT-BR translations, batch 2: ALifeDebugSpawner (admin spawn panel).
PT = {
'ALifeDebugSpawner.lua': {
    'Use profile': 'Usar perfil', 'Individual AI': 'IA individual', 'Fireteam coordination': 'Coordenação de equipe de fogo',
    'CQB entry team': 'Equipe de entrada (CQB)', 'Generalist': 'Generalista', 'Team leader': 'Líder de equipe', 'Medic': 'Médico',
    'Marksman': 'Atirador designado', 'Gunner / suppression': 'Metralhador / supressão', 'Use faction': 'Usar facção',
    'Ally -- friendly to players': 'Aliado -- amigável com os jogadores', 'Neutral -- leave players alone': 'Neutro -- deixa os jogadores em paz',
    'Careful -- warn, then shoot': 'Cauteloso -- avisa, depois atira', 'Hostile -- attack on sight': 'Hostil -- ataca ao avistar',
    'Yes': 'Sim', 'Automatic': 'Automático', 'North': 'Norte', 'North-east': 'Nordeste', 'East': 'Leste', 'South-east': 'Sudeste',
    'South': 'Sul', 'South-west': 'Sudoeste', 'West': 'Oeste', 'North-west': 'Noroeste',
    'Any squad member may call': 'Qualquer membro do esquadrão pode chamar', 'Radio operators only': 'Só operadores de rádio',
    'Nobody may call': 'Ninguém pode chamar', 'Ground + helicopter': 'Terrestre + helicóptero', 'Ground reinforcements': 'Reforços terrestres',
    'Helicopter only': 'Só helicóptero', 'No support at all': 'Nenhum apoio', 'No helicopter': 'Sem helicóptero', 'Spotlight only': 'Só holofote',
    'Helicopter support': 'Apoio de helicóptero', 'Right here': 'Bem aqui', 'Wherever the plan fits': 'Onde o plano couber',
    'Default -- just appear': 'Padrão -- só aparecem', 'Helicopter and rope': 'Helicóptero e corda', 'By car': 'De carro',
    'NPC faction': 'Facção de NPC', 'Encounter': 'Encontro', 'Behaviour doctrine': 'Doutrina de comportamento', 'Specialist role': 'Função especialista',
    'Stance toward players': 'Postura com os jogadores', 'Placement': 'Posicionamento', 'Arrival animation': 'Animação de chegada',
    'How they arrive': 'Como chegam', 'Save squad (within limit)': 'Salvar esquadrão (dentro do limite)', 'Invulnerable NPCs': 'NPCs invulneráveis',
    'Position locked': 'Posição travada', 'Facing / line heading': 'Direção / rumo da linha', 'Can call support': 'Pode chamar apoio',
    'Who may call': 'Quem pode chamar', 'Allowed support': 'Apoio permitido', 'Helicopter': 'Helicóptero', 'Group / wave size': 'Tamanho do grupo / onda',
    'Spawn distance': 'Distância de geração', 'Unit spacing': 'Espaçamento entre unidades', 'Behaviour radius': 'Raio de comportamento',
    'Detection range': 'Alcance de detecção', 'Movement leash': 'Limite de movimento', 'Exact HP': 'PV exatos', 'Damage reduction %': 'Redução de dano %',
    'Damage output %': 'Dano causado %', 'Support squad size': 'Tamanho do esquadrão de apoio', 'Support calls (max)': 'Chamadas de apoio (máx.)',
    'Support cooldown (h)': 'Recarga do apoio (h)', 'Raid waves (1-12)': 'Ondas da invasão (1-12)', 'Game minutes per wave': 'Minutos de jogo por onda',
    'Raid helicopter': 'Helicóptero da invasão', 'Weapon drop chance': 'Chance de largar arma', 'Weapon condition': 'Estado da arma',
    'Clothing condition': 'Estado das roupas', 'IDENTITY, AI & RULES': 'IDENTIDADE, IA E REGRAS', 'COMBAT, SUPPORT & EVENTS': 'COMBATE, APOIO E EVENTOS',
    'Any hostile faction': 'Qualquer facção hostil', 'Roaming squad (no encounter)': 'Esquadrão errante (sem encontro)',
    'Encounter arrows': 'Setas de encontro', 'Squads on the map': 'Esquadrões no mapa', 'Runtime status': 'Status de execução',
    'NPC report': 'Relatório de NPCs', 'Diagnostics': 'Diagnósticos', 'Repair runtime': 'Reparar execução', 'Black box dump': 'Despejar caixa-preta',
    'Module QA dump': 'Despejar QA dos módulos', 'No-spawn area here': 'Área sem geração aqui', 'Clear no-spawn areas': 'Limpar áreas sem geração',
    'Meta: gunfire': 'Ambiente: tiros', 'Meta: helicopter': 'Ambiente: helicóptero', 'Meta: ambience': 'Ambiente: sons', 'Meta: car crash': 'Ambiente: batida de carro',
    'Faction defaults': 'Padrões da facção', 'Reset fields': 'Redefinir campos', 'Load preset': 'Carregar predefinição', 'Save preset': 'Salvar predefinição',
    'Close': 'Fechar', 'SPAWN': 'GERAR', 'Pick a faction and an encounter, then press SPAWN.': 'Escolha uma facção e um encontro e aperte GERAR.',
    'Staffed outpost: ': 'Posto avançado com guarnição: ', ' hostile profiles ready.': ' perfis hostis prontos.',
    'Built at the clicked location. Saved site; session-only crew. Layout sets spacing.': 'Construído no local clicado. Local salvo; guarnição só desta sessão. O layout define o espaçamento.',
    'Roaming squad: the faction and the profile decide.': 'Esquadrão errante: a facção e o perfil decidem.', ' decides: program ': ' decide: programa ',
    ', leash ': ', limite ', ', holds ground': ', mantém posição', ', placed by its own rule': ', posicionado pela própria regra', ', placed here': ', posicionado aqui',
    'No saved presets': 'Nenhuma predefinição salva', 'Name the preset first.': 'Dê um nome à predefinição primeiro.', 'Preset saved: ': 'Predefinição salva: ',
    'No preset chosen.': 'Nenhuma predefinição escolhida.', 'Preset loaded: ': 'Predefinição carregada: ',
    "Fields reset to the profile's own settings.": 'Campos redefinidos para as configurações do perfil.',
    'Every override cleared -- the faction decides.': 'Todas as alterações apagadas -- a facção decide.', 'Building ': 'Construindo ',
    'The request could not be sent.': 'Não foi possível enviar a solicitação.', 'Spawning ': 'Gerando ', 'faction members': 'membros da facção',
    'Asking the server for the hostile catalog...': 'Pedindo ao servidor o catálogo de hostis...', 'Requesting runtime status...': 'Solicitando o status de execução...',
    'Encounter arrows toggled.': 'Setas de encontro alternadas.', 'Squad map opened.': 'Mapa de esquadrões aberto.', 'Meta event: ': 'Evento de ambiente: ',
    '  played locally (60 tiles north-east).': '  tocado localmente (60 quadrados a nordeste).', '  local play refused.': '  reprodução local recusada.',
    'Requesting the black box dump...': 'Solicitando o despejo da caixa-preta...', 'Requesting the module QA dump...': 'Solicitando o despejo do QA dos módulos...',
    'Running server diagnostics...': 'Executando diagnósticos do servidor...', 'Reading NPC behaviour and endurance...': 'Lendo comportamento e resistência dos NPCs...',
    'Repairing invalid runtime state...': 'Reparando estado de execução inválido...', 'Adding a protected no-spawn area...': 'Adicionando uma área protegida sem geração...',
    'Clearing the protected areas...': 'Limpando as áreas protegidas...', 'NPC FACTION  --  SPAWN': 'FACÇÃO DE NPC  --  GERAR',
    "Doctrine: use each profile's saved coordination behaviour.": 'Doutrina: usar o comportamento de coordenação salvo em cada perfil.',
    'Doctrine override: every member of this group runs it.': 'Doutrina forçada: todos os membros deste grupo a seguem.',
    'target ': 'alvo ', 'target: your position': 'alvo: sua posição', ' + complete ': ' + cena ', ' scene': ' completa',
    'Group queued: ': 'Grupo na fila: ', ' accepted, ': ' aceitos, ', ' rejected | ': ' rejeitados | ', 'Spawn rejected: ': 'Geração rejeitada: ',
    'Spawn progress: ': 'Progresso da geração: ', ' settled (': ' resolvidos (', ' active, ': ' ativos, ', ' failed)': ' falharam)',
    'Starting group member ': 'Iniciando membro do grupo ', 'Spawn job failed: ': 'Falha na geração: ', 'Group complete: ': 'Grupo completo: ',
    ' failed | ': ' falharam | ', 'no group id': 'sem id de grupo', 'Diagnostics healthy: ': 'Diagnóstico OK: ',
    'Diagnostics found faults: ': 'Diagnóstico encontrou falhas: ', ' error(s), ': ' erro(s), ', ' warning(s), ': ' aviso(s), ',
    ' admin spawn(s) pending.': ' geração(ões) de admin pendente(s).', 'Movement: ': 'Movimento: ', ' paths, ': ' rotas, ', ' stalls, ': ' travamentos, ',
    ' traversal failure(s), ': ' falha(s) de travessia, ', ' unreachable target(s).': ' alvo(s) inalcançável(is).', 'NPC inspector: ': 'Inspetor de NPCs: ',
    ' actor(s), ': ' ator(es), ', '...additional actors omitted from this panel.': '...atores adicionais omitidos deste painel.',
    'Catalog error: ': 'Erro no catálogo: ', '  server fired meta ': '  o servidor disparou o evento ', '  server refused meta ': '  o servidor recusou o evento ',
    'the SERVER log': 'o log do SERVIDOR', '; client recorder in your console.txt': '; gravador do cliente no seu console.txt',
    'Module QA written to ': 'QA dos módulos gravado em ', 'Black box written to ': 'Caixa-preta gravada em ', ' dump failed: ': ' - despejo falhou: ',
    'unknown': 'desconhecido', 'Repair: ': 'Reparo: ', ' fixed, ': ' corrigidos, ', ' failed; health ': ' falharam; saúde ', 'needs review': 'precisa de revisão',
    'Protected area added.': 'Área protegida adicionada.', 'Protection failed: ': 'Falha ao proteger: ', 'Cleared ': 'Limpas: ',
    ' protected area(s).': ' área(s) protegida(s).', 'Clear failed: ': 'Falha ao limpar: ', 'disabled': 'desativado', 'enabled': 'ativado',
    ' | health ': ' | saúde ', ' error(s)': ' erro(s)', ' | actors ': ' | atores ', ' | shells ': ' | corpos ', ' | pending ': ' | pendentes ',
},
}
