# PT-BR translations, batch 4: display strings the Spanish translation did not cover
# (new in the current upstream build, or files it never touched).
# SCAN = True: entries are created by scanning the upstream file for each key
# ("en" = every literal with that text, "en||ctx-suffix" = only that anchor).
SCAN = True
# Only literals whose context ends with this are considered in these files.
DEFAULT_CTX = {'ALifeDialogueRoles.lua': 'label =', 'ALifeVoiceCatalog.lua': 'label ='}

PT = {
'ALifeCreatorScreen.lua': {
    'Neutral||"friendly" } , {': 'Neutro', 'No||"yes" } , {': 'Não',
    'Any season': 'Qualquer estação', 'Spring only': 'Só na primavera', 'Summer only': 'Só no verão',
    'Autumn only': 'Só no outono', 'Winter only': 'Só no inverno',
    'Unarmed': 'Desarmado', 'Empty': 'Vazio',
    # glyph lookup compares the tile title; titles are translated, so the comparisons follow
    'VEST||self . title ==': 'COLETE', 'BACK||self . title ==': 'COSTAS', 'HAT||self . title ==': 'CHAPÉU',
    'SIDEARM||self . title ==': 'SECUNDÁRIA', 'MELEE / BELT||self . title ==': 'CORPO A CORPO / CINTO',
    '  OFF': '  DESLIGADO', ' COLOR: ': ' - COR: ', 'COMPATIBLE': 'COMPATÍVEL', ' audio': ' áudio', 'AUDIO ': 'ÁUDIO ',
    'COPY NPC FOLDER': 'COPIAR PASTA DE NPCS', 'FOLDER COPY FAILED - COULD NOT SAVE': 'FALHA AO COPIAR PASTA - NÃO FOI POSSÍVEL SALVAR',
    'FOLDER COPIED - FACTIONS: ': 'PASTA COPIADA - FACÇÕES: ', 'Unfiled': 'Sem pasta', '  -  ACTIVE': '  -  ATIVA',
    ' preset': ' predefinição', ' presets': ' predefinições', 'New Faction': 'Nova facção',
    'RESET FAILED - DEFAULT FACTIONS NOT LOADED': 'FALHA AO REDEFINIR - FACÇÕES PADRÃO NÃO CARREGADAS',
    'FACTIONS RESET TO DEFAULT': 'FACÇÕES REDEFINIDAS PARA O PADRÃO', 'RESET FAILED - COULD NOT SAVE': 'FALHA AO REDEFINIR - NÃO FOI POSSÍVEL SALVAR',
    'Are you sure?\nBuilt-in factions go back to default and deleted ones come back.\nFactions you made yourself stay.':
        'Tem certeza?\nAs facções embutidas voltam ao padrão e as excluídas reaparecem.\nAs facções que você criou continuam.',
    'Accuracy vs players (%)': 'Precisão contra jogadores (%)', 'Accuracy vs zombies (%)': 'Precisão contra zumbis (%)',
    'ALL||"makeup" } , {': 'TODOS', ' weight': ' peso',
    'Any season: this set can spawn all year. A season: it only spawns then, and in that season it replaces the any-season sets. The date is checked when the NPC is first created. Winter is Dec-Feb, spring Mar-May, summer Jun-Aug, autumn Sep-Nov.':
        'Qualquer estação: este conjunto pode aparecer o ano todo. Uma estação: só aparece nela e, nessa estação, substitui os conjuntos de qualquer estação. A data é verificada quando o NPC é criado. No jogo (hemisfério norte), inverno é dez-fev, primavera mar-mai, verão jun-ago e outono set-nov.',
    ' choices': ' opções', ' total': ' no total', 'ROSTER': 'LISTA', 'DIRECTOR: ': 'DIRETOR: ',
    'RESET FACTIONS TO DEFAULT': 'REDEFINIR FACÇÕES PARA O PADRÃO',
    'Built-in factions go back to default. Factions you made yourself stay.': 'As facções embutidas voltam ao padrão. As facções que você criou continuam.',
},
'ALifeCustomFactions.lua': {'New Faction': 'Nova facção', 'Player-created Project A-Life faction.': 'Facção do Project A-Life criada pelo jogador.'},
'ALifeCustomProfiles.lua': {'Custom NPC': 'NPC personalizado'},
'ALifeDebugSpawner.lua': {'No': 'Não', 'Normal': 'Normal', 'black box': 'caixa-preta'},
'ALifeEncounterConsole.lua': {' scene': '', 'black box': 'caixa-preta', 'DIRECTOR': 'DIRETOR'},
'ALifeStatusWindow.lua': {'Offline squads on the map: ': 'Esquadrões offline no mapa: ', 'Offline founded / refused: ': 'Offline criados / recusados: ',
    'Encounter rolls / spawned: ': 'Encontros sorteados / gerados: ', 'Runtime: ': 'Execução: '},
'ALifeContextMenu.lua': {'Invulnerable': 'Invulnerável', 'A-Life: session siren': 'A-Life: sirene da sessão',
    'A-Life: meta event ': 'A-Life: evento de ambiente ', 'A-Life: world audio silenced (': 'A-Life: áudio do mundo silenciado (',
    'Dump NPC blackbox to console.txt': 'Despejar caixa-preta dos NPCs em console.txt'},
'ALifeEncounterCompass.lua': {'A-Life: encounter arrows ON': 'A-Life: setas de encontro LIGADAS', 'A-Life: encounter arrows OFF': 'A-Life: setas de encontro DESLIGADAS'},
'ALifeRaidClient.lua': {'THIS IS HOW YOU DIED': 'FOI ASSIM QUE VOCÊ MORREU', 'YOUR LAST STAND BEGINS': 'SUA ÚLTIMA RESISTÊNCIA COMEÇA'},
'ALifeSupportClient.lua': {'Is that a helicopter?': 'Aquilo é um helicóptero?', 'You can see a helicopter rappeling people': 'Você vê um helicóptero descendo gente de rapel'},
'ALifeTalkIntents.lua': {'Maybe we can work together?': 'Talvez a gente possa trabalhar junto?'},
'ALifeRaidDirector.lua': {'FULL SCALE RAID': 'INVASÃO EM GRANDE ESCALA'},
'ALifeDebugService.lua': {
    'Moves through the area and attacks threats it detects.': 'Percorre a área e ataca as ameaças que detecta.',
    'Circulates around the spawn point and returns to its route.': 'Circula em volta do ponto de geração e volta à sua rota.',
    'Searches nearby containers, collects supplies, then continues.': 'Revista contêineres próximos, recolhe suprimentos e segue em frente.',
    'Actively searches the local area for hostile targets.': 'Procura ativamente alvos hostis na área.',
    'Tracks the designated player and keeps re-engaging.': 'Rastreia o jogador designado e continua voltando ao ataque.',
    'Treats the spawn point as home and defends its radius.': 'Trata o ponto de geração como lar e defende os arredores.',
    'Stays around a temporary camp and defends the perimeter.': 'Fica em volta de um acampamento temporário e defende o perímetro.',
    'Cars across the road, a line of guns behind them.': 'Carros atravessados na estrada e uma fileira de armas atrás deles.',
    'Patrols and defends a persistent outpost anchor.': 'Patrulha e defende um posto avançado persistente.',
    'Advances on nearby players as an attacking group.': 'Avança sobre jogadores próximos como grupo de ataque.',
    'Runs a sustained coordinated attack against players.': 'Faz um ataque coordenado e prolongado contra jogadores.',
    'Wilderness camp': 'Acampamento na mata', 'Builds the complete campsite and stages its squad in one plan.': 'Monta o acampamento completo e posiciona o esquadrão num só plano.',
    'the SERVER log (coop-console.txt for a co-op host)': 'o log do SERVIDOR (coop-console.txt para quem hospeda co-op)',
    ' squad(s) sent out': ' esquadrão(ões) enviado(s)', 'site is ': 'local está ', 'forming up nearby': 'se reunindo por perto',
    'on the road': 'na estrada', ' to ||text = text ..': ' rumo a ', 'resting||then return': 'descansando', 'scavenging||then return': 'coletando',
    'reinforcing an outpost': 'reforçando um posto avançado', 'patrolling||then return': 'patrulhando', 'waiting for orders': 'aguardando ordens',
    'outpost squad': 'esquadrão de posto avançado', 'garrison of ': 'guarnição de ', 'fighting||{ combat =': 'lutando',
    'warning someone off': 'mandando alguém se afastar', 'moving||moving =': 'em movimento', 'idle||idle =': 'parado', 'dead||dead =': 'morto',
    'A-Life: support called (': 'A-Life: apoio chamado (', 'A-Life: support refused (': 'A-Life: apoio recusado (',
    'A-Life: full raid started': 'A-Life: invasão total iniciada', 'A-Life: raid refused (': 'A-Life: invasão recusada (',
    'A-Life: outpost built, ': 'A-Life: posto avançado construído, ', ' ops, squad ': ' operações, esquadrão ',
    'spawned||garrisoned and': 'gerado', 'pending||"spawned" or': 'pendente', 'A-Life: outpost refused (': 'A-Life: posto avançado recusado (',
    'A-Life: full-scale raid started (': 'A-Life: invasão em grande escala iniciada (', 'Admin protected area': 'Área protegida pelo admin',
},
'ALifeDropPolicy.lua': {
    'Broken (0/10)': 'Quebrado (0/10)', 'Scrap, a shot or two (1/10)': 'Sucata, um ou dois tiros (1/10)',
    'Very poor, a few shots (2/10)': 'Muito ruim, poucos tiros (2/10)', 'Poor (3/10)': 'Ruim (3/10)', 'Worn (4/10)': 'Gasto (4/10)',
    'Used, half gone (5/10)': 'Usado, meio gasto (5/10)', 'Serviceable (6/10)': 'Utilizável (6/10)', 'Good (7/10)': 'Bom (7/10)',
    'Very good (8/10)': 'Muito bom (8/10)', 'Near new (9/10)': 'Quase novo (9/10)', 'Issue fresh (10/10)': 'Novo em folha (10/10)',
    'Off (0%)': 'Desligado (0%)', 'Very low (0-10%)': 'Muito baixa (0-10%)', 'Low (10-20%)': 'Baixa (10-20%)', 'Moderate (20-30%)': 'Moderada (20-30%)',
    'High (30-50%)': 'Alta (30-50%)', 'Very high (50-70%)': 'Muito alta (50-70%)', 'Almost always (70-99%)': 'Quase sempre (70-99%)', 'Always (100%)': 'Sempre (100%)',
},
'ALifeEncounters.lua': {
    'A small armed group walking a real circuit, abreast, pausing at the corners. Warns before it shoots.': 'Um pequeno grupo armado percorrendo um circuito de verdade, lado a lado, parando nas esquinas. Avisa antes de atirar.',
    'An attacking group that pushes at the nearest players.': 'Um grupo de ataque que avança sobre os jogadores mais próximos.',
    'A big, sustained, coordinated push. Rare and loud.': 'Um ataque grande, prolongado e coordenado. Raro e barulhento.',
    "A wreck on the road and the survivors of it -- any faction's people.": 'Um acidente na estrada e os sobreviventes dele -- gente de qualquer facção.',
    'A tracker and a rifle: quiet approach, one loud second.': 'Um rastreador e um rifle: aproximação silenciosa, um segundo barulhento.',
    'Cars across the road and a line of guns behind them, holding the crossing. They do not chase far.': 'Carros atravessados na estrada e uma fileira de armas atrás deles, segurando a passagem. Não perseguem para longe.',
    'Hidden guns on both shoulders of a road, holding fire until something drives into the middle.': 'Armas escondidas nos dois acostamentos de uma estrada, esperando até que algo entre no meio.',
    'A pair of rifles on an upper floor, working the street below and refusing to come down.': 'Dois rifles num andar de cima, cobrindo a rua lá embaixo e se recusando a descer.',
    'A crew that has taken somewhere worth taking -- a station, a warehouse -- and means to keep it.': 'Um grupo que tomou um lugar que valia a pena -- uma delegacia, um armazém -- e pretende mantê-lo.',
    'A dead engine, an empty tank, one pair of hands under the bonnet and the rest of them watching the road.': 'Motor morto, tanque vazio, um mexendo embaixo do capô e o resto vigiando a estrada.',
    'A circuit of the same four corners, walked all day. Predictable on purpose: it can be learned.': 'Um circuito pelas mesmas quatro esquinas, percorrido o dia todo. Previsível de propósito: dá para aprender.',
    'A crew out for one thing -- medicine, food, ammunition or tools -- working a street house by house behind its leader, in through doors only.': 'Um grupo atrás de uma coisa só -- remédio, comida, munição ou ferramentas -- vasculhando a rua casa por casa atrás do líder, entrando só pelas portas.',
    'People who live here. They hold the inside of the building, they do not breach out, and they do not leave.': 'Gente que mora aqui. Defendem o interior do prédio, não saem para fora e não vão embora.',
},
'ALifeBehaviorProfiles.lua': {
    'Roams between contacts, then hunts the nearest hostile and keeps pressure on it.': 'Vaga entre contatos, depois caça o hostil mais próximo e mantém a pressão.',
    'Holds a route around its anchor and warns players off.': 'Mantém uma rota em volta do seu ponto e manda os jogadores se afastarem.',
    'Works containers for supplies and investigates noises.': 'Revista contêineres atrás de suprimentos e investiga ruídos.',
    'Moves and fights as part of a group.': 'Anda e luta como parte de um grupo.',
    'Tracks players specifically and re-engages relentlessly.': 'Rastreia especificamente jogadores e volta ao ataque sem parar.',
    'TEST -- every module': 'TESTE -- todos os módulos', 'Permits every behaviour module at once. For testing only.': 'Permite todos os módulos de comportamento ao mesmo tempo. Só para testes.',
},
'ALifeModuleCareful.lua': {'A faction that is careful with the player warns at range, warns again closer, and turns hostile when the warnings are walked through or shouted over.': 'Uma facção cautelosa com o jogador avisa de longe, avisa de novo mais perto e fica hostil quando os avisos são ignorados ou respondidos aos gritos.'},
'ALifeModuleConducts.lua': {
    'Shadows a person from behind, sneaking, and opens with a backstab at double damage. Picks locks instead of breaching.': 'Segue uma pessoa por trás, furtivamente, e abre com uma facada nas costas de dano dobrado. Arromba fechaduras em vez de derrubar portas.',
    'Keeps distance, gives ground when the fight closes, and fires deliberate single shots.': 'Mantém distância, recua quando a luta chega perto e dá tiros únicos e calculados.',
    "Finds the group's wounded after a fight, walks over, and dresses their wounds with its own bandages.": 'Depois de uma luta, encontra os feridos do grupo, vai até eles e trata os ferimentos com as próprias ataduras.',
    'Takes a hidden position, holds fire, and springs when the target walks in close.': 'Fica numa posição escondida, segura o fogo e ataca quando o alvo chega perto.',
    'Shooters sidestep left and right while trading fire with people.': 'Atiradores se deslocam para os lados enquanto trocam tiros com pessoas.',
    'Squad members keep a couple of tiles of air between each other.': 'Membros do esquadrão mantêm uns dois quadrados de distância entre si.',
},
'ALifeModuleCover.lua': {'Shooters get out of the line of fire to reload, break contact when hurt, and fight from behind walls.': 'Atiradores saem da linha de tiro para recarregar, rompem o contato quando feridos e lutam atrás de paredes.'},
'ALifeModuleFlanking.lua': {'Gives ranged actors stable approach lanes and wider wings at long range.': 'Dá aos atiradores à distância rotas de aproximação estáveis e alas mais abertas a longa distância.'},
'ALifeModuleFortify.lua': {'A garrison boards up its own windows and doors from the inside, leaving its entrance clear.': 'Uma guarnição tapa com tábuas as próprias janelas e portas por dentro, deixando a entrada livre.'},
'ALifeModuleGunner.lua': {'A shooter that loses its line dumps the magazine into the last known position, full auto, spraying left and right.': 'Um atirador que perde a linha de tiro esvazia o carregador na última posição conhecida, no automático, varrendo para os lados.'},
'ALifeModuleHealing.lua': {'A wounded actor stops after the fight, bandages, and loses the limp and the bleeding.': 'Um ator ferido para depois da luta, faz curativo e deixa de mancar e sangrar.'},
'ALifeModuleIdleLife.lua': {'Eats, drinks and smokes between fights; at night a stance-less squad may board up a house and stay till morning.': 'Come, bebe e fuma entre as lutas; à noite um esquadrão sem postura definida pode fechar uma casa com tábuas e ficar até de manhã.'},
'ALifeModuleLeader.lua': {'Keeps the group together, deploys it on contact and rallies it after losses. Orders never delay shooting; its death scatters the group.': 'Mantém o grupo unido, posiciona-o no contato e o reagrupa depois de baixas. Ordens nunca atrasam os tiros; a morte dele dispersa o grupo.'},
'ALifeModuleNightHold.lua': {'A house crew goes quiet after dark -- sits, eats, talks, ignores the dead outside -- wakes when a player comes to the walls, and clears the yard at dawn.': 'O grupo da casa fica quieto depois que escurece -- senta, come, conversa, ignora os mortos lá fora --, desperta quando um jogador chega às paredes e limpa o quintal ao amanhecer.'},
'ALifeModulePanic.lua': {'The first sight of a person is a beat of disorder: a shout, a dash for cover or a freeze, near rounds pin, the leader steadies the line. Once per engagement, once per squad per minute; never zombies.': 'Ver uma pessoa pela primeira vez causa um instante de desordem: um grito, uma corrida para a cobertura ou um congelamento, tiros próximos prendem no lugar, o líder estabiliza a linha. Uma vez por confronto, uma vez por esquadrão por minuto; nunca com zumbis.'},
'ALifeModulePatrolRest.lua': {'The squad stops off the road, stands in a circle, sits, smokes, drinks and talks; then the route resumes.': 'O esquadrão para fora da estrada, fica em roda, senta, fuma, bebe e conversa; depois retoma a rota.'},
'ALifeModuleRobbery.lua': {'Robbery||label =': 'Assalto', 'An outlaw crew holds up a lone player: weapon down, hands up, three or four valuable items taken, then it leaves. Refusing gets him shot.': 'Um grupo fora da lei rende um jogador sozinho: arma no chão, mãos para cima, três ou quatro itens valiosos levados, e depois vai embora. Quem recusar leva tiro.'},
'ALifeModuleScavengeRun.lua': {'Scavenge||label =': 'Coleta', 'Works a nearby building end to end, falling back to loose containers.': 'Vasculha um prédio próximo de ponta a ponta e, se não der, contêineres soltos.'},
'ALifeModuleSearch.lua': {'Search||label =': 'Revista', 'After combat, search up to two bodies for a bounded share of non-clothing loot.': 'Depois do combate, revista até dois corpos atrás de uma parte limitada do saque que não seja roupa.'},
'ALifeModuleStances.lua': {'Holds the post an encounter was spawned for: garrisons, roadblocks, routes, upper floors, a broken car.': 'Mantém o posto para o qual o encontro foi gerado: guarnições, bloqueios, rotas, andares de cima, um carro quebrado.'},
'ALifeModuleStrafe.lua': {'Shooters keep the gun on the target, or where it was last seen, while they walk.': 'Atiradores mantêm a arma no alvo, ou onde ele foi visto por último, enquanto andam.'},
'ALifeModuleSurvival.lua': {'Flee||label =': 'Fugir', 'The unarmed run from guns -- twice; and the badly wounded break off.': 'Os desarmados fogem de armas -- duas vezes; e os gravemente feridos abandonam a luta.'},
'ALifeModuleTalkPresence.lua': {'Answers a player who talks, greets without stopping, says a word when passing, and calls out a stranger when it is an outlaw crew.': 'Responde a um jogador que fala, cumprimenta sem parar, diz alguma coisa ao passar e confronta um estranho quando é um grupo fora da lei.'},
'ALifeModuleTravel.lua': {
    'Obeys hold/move orders issued by an admin or the director.': 'Obedece a ordens de parar/mover dadas por um admin ou pelo diretor.',
    'Walks toward gunfire and other sounds it did not make.': 'Vai na direção de tiros e outros sons que não fez.',
    'Closes back up with the rest of the group when it drifts apart.': 'Volta a se juntar ao resto do grupo quando se afasta.',
    'Shares one travel heading with the rest of the group.': 'Segue a mesma direção de viagem que o resto do grupo.',
},
'ALifeModuleWithdraw.lua': {'A losing shooter breaks contact, holes up out of sight, then comes back in from another side.': 'Um atirador em desvantagem rompe o contato, se esconde fora de vista e depois volta por outro lado.'},
'ALifeVoiceCatalog.lua': {'Calm Male': 'Masculina calma', 'Calm Female': 'Feminina calma', 'Aggressive Male': 'Masculina agressiva', 'Aggressive Female': 'Feminina agressiva'},
'ALifeDialogueRoles.lua': {
    'Family - Man': 'Família - Homem', 'Family - Woman': 'Família - Mulher', 'Family - Elder': 'Família - Idoso', 'Family - Young Adult': 'Família - Jovem adulto',
    'Civilian - Survivor': 'Civil - Sobrevivente', 'Civilian - Survivor Woman': 'Civil - Sobrevivente mulher', 'Civilian - Loner': 'Civil - Solitário',
    'Worker': 'Trabalhador', 'Rescue - Firefighter': 'Resgate - Bombeiro', 'Rescue - Medical': 'Resgate - Socorrista', 'Rescue - Clergy': 'Resgate - Religioso',
    'Law Enforcement - Deputy Sheriff': 'Forças da Lei - Xerife adjunto', 'Law Enforcement - Sheriff': 'Forças da Lei - Xerife',
    'Law Enforcement - Police Officer': 'Forças da Lei - Policial', 'Law Enforcement - Sergeant': 'Forças da Lei - Sargento',
    'Law Enforcement - State Trooper': 'Forças da Lei - Patrulheiro estadual', 'Law Enforcement - Corrections Officer': 'Forças da Lei - Agente penitenciário',
    'Law Enforcement - SWAT Team Leader': 'Forças da Lei - Líder da SWAT', 'Law Enforcement - SWAT Operator': 'Forças da Lei - Operador da SWAT',
    'Military - Soldier': 'Militar - Soldado', 'Military - Sergeant': 'Militar - Sargento', 'Military - Trainee': 'Militar - Recruta', 'Military - Deserter': 'Militar - Desertor',
    'Militia - Rifleman': 'Milícia - Fuzileiro', 'Special Forces - Operator': 'Forças Especiais - Operador', 'Delta - Operator': 'Delta - Operador',
    'Outlaw': 'Fora da lei', 'Raider': 'Saqueador', 'Raider - Boss': 'Saqueador - Chefe', 'Gang - Soldier': 'Gangue - Soldado', 'Gang - Shot Caller': 'Gangue - Mandachuva',
    'Motorcycle Club - Member': 'Motoclube - Membro', 'Motorcycle Club - President': 'Motoclube - Presidente', 'Crime - Associate': 'Crime - Comparsa',
    'Prison - Escapee': 'Prisão - Fugitivo', 'Mercenary': 'Mercenário',
},
}
