# PT-BR translations, batch 3: ALifeCreatorScreen (faction & NPC Creator).
# Anchors whose context matches SKIP_CTX are left in English: they are the button
# words Creator.playUiSound matches on; PT words are added to that check by a code patch.
SKIP_CTX = {'ALifeCreatorScreen.lua': [r'text : find \(', r'or text ==', r'Creator\.upper\(', r'string \. upper \(']}

PT = {
'ALifeCreatorScreen.lua': {
    # encounter kinds / outposts / programs
    'Roaming survivors': 'Sobreviventes errantes', 'Travel between places': 'Viajam entre lugares', 'Patrol': 'Patrulha',
    'An open-area route': 'Uma rota em área aberta', 'Town patrol': 'Patrulha urbana', 'Streets and neighborhoods': 'Ruas e bairros',
    'Scavengers': 'Catadores', 'Search for supplies': 'Procuram suprimentos', 'Camps': 'Acampamentos',
    'Outdoor survivor camps': 'Acampamentos de sobreviventes ao ar livre', 'Outposts & residents': 'Postos avançados e moradores',
    'Bases and building garrisons': 'Bases e guarnições em prédios', 'Station guards': 'Guardas de delegacia',
    'Protect important buildings': 'Protegem prédios importantes', 'Rooftop shooters': 'Atiradores no telhado',
    'Hold elevated positions': 'Seguram posições elevadas', 'Roadblock': 'Bloqueio na estrada', 'Defend a stretch of road': 'Defendem um trecho de estrada',
    'Broken-down car': 'Carro quebrado', 'Stranded repair crew': 'Equipe de reparo presa', 'Road crash': 'Acidente na estrada',
    'Triggered by world events': 'Disparado por eventos do mundo', 'Highway ambush': 'Emboscada na rodovia', 'Triggered by driving': 'Disparada ao dirigir',
    'Enemy scouts': 'Batedores inimigos', 'Hostile reconnaissance': 'Reconhecimento hostil', 'Assassination': 'Assassinato',
    'Hunt a target': 'Caçam um alvo', 'Full-scale raid': 'Invasão em grande escala', 'Scout buildup + raid-day rules': 'Preparação de batedores + regras do dia da invasão',
    'Holdout': 'Reduto', 'A house a family holds': 'Uma casa ocupada por uma família', 'Walled compound': 'Complexo murado',
    'A walled settlement': 'Um assentamento murado', 'Fortified station': 'Delegacia fortificada', 'A station turned into a base': 'Uma delegacia transformada em base',
    'Held house': 'Casa ocupada', 'A sturdy house, garrisoned': 'Uma casa resistente, com guarnição', 'Fortified field base': 'Base de campo fortificada',
    'A built camp in the open': 'Um acampamento construído ao ar livre', 'Forest camp': 'Acampamento na floresta', 'A camp under the trees': 'Um acampamento sob as árvores',
    'Field aid station': 'Posto de primeiros socorros', 'A place that treats people': 'Um lugar que cuida de feridos', 'Supply depot': 'Depósito de suprimentos',
    'Stores, and people guarding them': 'Estoques e gente vigiando', 'Checkpoint': 'Posto de controle', 'A bridge or road cordon': 'Um bloqueio em ponte ou estrada',
    'Patrol / guard': 'Patrulhar / vigiar', 'Scavenge / loot': 'Vasculhar / saquear', 'Roam': 'Vagar',
    'Hunt||"roam" } , {': 'Caçar', 'Hunt||"guard" } , {': 'Caçada', 'Manhunt': 'Caçada humana',
    'Police & prisons': 'Polícia e prisões', 'Fire stations': 'Quartéis de bombeiros', 'Hospitals & clinics': 'Hospitais e clínicas',
    'Warehouses': 'Armazéns', 'Gun & military sites': 'Lojas de armas e locais militares',
    # voices
    'Male': 'Masculino', 'Female': 'Feminino', 'Automatic  /  faction voice': 'Automático  /  voz da facção',
    'Outlaw Survivor 1': 'Sobrevivente fora da lei 1', 'Outlaw Survivor 2': 'Sobrevivente fora da lei 2', 'Outlaw Survivor 3': 'Sobrevivente fora da lei 3',
    'Experienced Survivor 1': 'Sobrevivente experiente 1', 'Experienced Survivor 2': 'Sobrevivente experiente 2', 'Experienced Survivor 3': 'Sobrevivente experiente 3',
    'Paramilitary Survivor 1': 'Sobrevivente paramilitar 1', 'Paramilitary Survivor 2': 'Sobrevivente paramilitar 2', 'Paramilitary Survivor 3': 'Sobrevivente paramilitar 3',
    'Scientist 1': 'Cientista 1', 'Scientist 2': 'Cientista 2', 'Scientist 3': 'Cientista 3',
    'Anarchist Survivor 1': 'Sobrevivente anarquista 1', 'Anarchist Survivor 2': 'Sobrevivente anarquista 2', 'Anarchist Survivor 3': 'Sobrevivente anarquista 3',
    'Military Soldier 1': 'Soldado militar 1', 'Military Soldier 2': 'Soldado militar 2', 'Military Soldier 3': 'Soldado militar 3',
    'Foreign Survivor 1': 'Sobrevivente estrangeiro 1', 'Foreign Survivor 2': 'Sobrevivente estrangeiro 2', 'Foreign Survivor 3': 'Sobrevivente estrangeiro 3',
    'Mercenary 1': 'Mercenário 1', 'Mercenary 2': 'Mercenário 2', 'Mercenary 3': 'Mercenário 3', 'Mercenary 4': 'Mercenário 4',
    'Mercenary 5': 'Mercenário 5', 'Mercenary 6': 'Mercenário 6', 'Mercenary 7': 'Mercenário 7', 'Mercenary 8': 'Mercenário 8',
    'Law Enforcement - Team Lead': 'Forças da Lei - Líder de equipe', 'Law Enforcement - Operator 1': 'Forças da Lei - Operador 1',
    'Law Enforcement - Operator 2': 'Forças da Lei - Operador 2', 'Law Enforcement - Operator 3': 'Forças da Lei - Operador 3',
    'Law Enforcement - Operator 4': 'Forças da Lei - Operador 4', 'American Survivor 1': 'Sobrevivente americano 1',
    'American Survivor 2': 'Sobrevivente americano 2', 'American Survivor 3': 'Sobrevivente americano 3', 'Russian Survivor 1': 'Sobrevivente russo 1',
    'Russian Survivor 2': 'Sobrevivente russo 2', 'Russian Survivor 3': 'Sobrevivente russo 3', 'Foreign Female Survivor': 'Sobrevivente estrangeira',
    'American Female Survivor': 'Sobrevivente americana',
    # roles / tiers / programs
    'Scout': 'Batedor', 'Guard': 'Guarda', 'Raider': 'Saqueador', 'Heavy': 'Pesado', 'Medic': 'Médico', 'Leader': 'Líder', 'Sniper': 'Atirador de elite',
    'Scavenger': 'Catador', 'Radio operator': 'Operador de rádio', 'Breacher': 'Arrombador', 'Mechanic': 'Mecânico', 'Driver': 'Motorista',
    'Quartermaster': 'Intendente', 'Hunter': 'Caçador', 'Civilian': 'Civil', 'Recruit': 'Recruta', 'Veteran': 'Veterano', 'Elite': 'Elite',
    'Patrol / Scavenge': 'Patrulha / Coleta', 'Scavenge': 'Coleta', 'Assault': 'Assalto', 'Full Raid': 'Invasão total',
    'Brain module': 'Módulo de cérebro', 'Perception module': 'Módulo de percepção', 'Movement module': 'Módulo de movimento', 'Combat module': 'Módulo de combate',
    'Scavenging module': 'Módulo de coleta', 'Voice module': 'Módulo de voz', 'Encounter module': 'Módulo de encontros', 'Raid module': 'Módulo de invasões',
    'Relations module': 'Módulo de relações', 'Director module': 'Módulo diretor',
    'Allied': 'Aliado', 'Friendly': 'Amigável', 'Careful': 'Cauteloso', 'Hostile': 'Hostil', 'Magazines': 'Carregadores',
    'Default (Mixed)': 'Padrão (Misto)', 'Yes': 'Sim', 'Mixed': 'Misto',
    'None||PRIMARY_BEHAVIORS = { {': 'Nenhuma', 'Gunner': 'Metralhador', 'Stealth': 'Furtivo', 'Ambusher': 'Emboscador',
    # behavior modules
    'Follow orders': 'Seguir ordens', 'Hold stance': 'Manter postura', 'Panic': 'Pânico', 'Withdraw': 'Recuar', 'Flee': 'Fugir',
    'Strafe': 'Deslocamento lateral', 'Weave': 'Zigue-zague', 'Cover': 'Cobertura', 'Door stack': 'Formação na porta', 'CQB sweep': 'Varredura CQB',
    'Flanking': 'Flanqueio', 'Healing': 'Cura', 'Search': 'Revista', 'Investigate': 'Investigar', 'Idle life': 'Vida cotidiana',
    'Regroup': 'Reagrupar', 'Group march': 'Marcha em grupo', 'Spread': 'Espalhar', 'Patrol rest': 'Descanso da patrulha', 'Rob players': 'Assaltar jogadores',
    "Follow the leader's current order instead of selecting an unrelated task.": 'Seguir a ordem atual do líder em vez de escolher uma tarefa sem relação.',
    'Hold the assigned guard, route, blockade or garrison stance until the squad changes it.': 'Manter a postura designada de guarda, rota, bloqueio ou guarnição até o esquadrão mudá-la.',
    'React to overwhelming danger and recover after reaching a safer distance.': 'Reagir a um perigo esmagador e se recuperar depois de chegar a uma distância mais segura.',
    'Back away while facing and aiming at the threat; fire remains available during the retreat.': 'Recuar encarando e mirando na ameaça; ainda pode atirar durante o recuo.',
    'Allow a full break-contact escape. The world Flee switch must also be enabled; a faction or NPC override cannot bypass it.': 'Permitir uma fuga completa, rompendo o contato. A chave global de Fuga também precisa estar ativada; uma alteração de facção ou de NPC não consegue contorná-la.',
    'Move laterally while keeping the weapon and attention on the current target.': 'Mover-se para os lados mantendo a arma e a atenção no alvo atual.',
    'Vary the approach path under fire instead of running in one predictable line.': 'Variar o caminho de aproximação sob fogo em vez de correr numa linha previsível.',
    'Search for nearby cover and fight from it when the path and line of fire are valid.': 'Procurar cobertura próxima e lutar a partir dela quando o caminho e a linha de tiro forem válidos.',
    'Queue at an entrance so squad members do not jam the same doorway.': 'Fazer fila numa entrada para que os membros do esquadrão não se amontoem na mesma porta.',
    'Clear close interior spaces in a controlled room-to-room sequence.': 'Limpar espaços internos fechados numa sequência controlada, cômodo por cômodo.',
    "Move to a side angle when another squad member already occupies the target's attention.": 'Ir para um ângulo lateral quando outro membro do esquadrão já estiver ocupando a atenção do alvo.',
    'Treat wounds during a safe pause and return to the previous squad task afterwards.': 'Tratar ferimentos numa pausa segura e depois voltar à tarefa anterior do esquadrão.',
    'Search valid containers, reserve loot and carry useful supplies for the squad.': 'Revistar contêineres válidos, reservar o saque e carregar suprimentos úteis para o esquadrão.',
    'After combat, search at most two bodies (at most one infected). Take a bounded quarter of non-clothing items, prioritizing weapons. Gear remains recoverable.': 'Depois do combate, revistar no máximo dois corpos (no máximo um infectado). Levar até um quarto dos itens que não são roupas, priorizando armas. O equipamento continua recuperável.',
    'Inspect recent sounds, sightings and clues without forgetting the squad objective.': 'Averiguar sons, avistamentos e pistas recentes sem esquecer o objetivo do esquadrão.',
    'Use believable calm-state activities while no urgent task or threat is active.': 'Fazer atividades cotidianas críveis enquanto não houver tarefa urgente nem ameaça ativa.',
    'Return isolated members to a safe formation around the squad leader.': 'Trazer membros isolados de volta a uma formação segura ao redor do líder do esquadrão.',
    'Travel as a formation instead of sending every member through an independent path.': 'Viajar em formação em vez de mandar cada membro por um caminho independente.',
    'Maintain useful spacing so the squad does not form a single vulnerable cluster.': 'Manter um espaçamento útil para que o esquadrão não forme um único aglomerado vulnerável.',
    'Let patrols pause together for rest, idle activities and conversation. Rest timing and the master switch come from sandbox settings.': 'Deixar as patrulhas pararem juntas para descansar, fazer atividades cotidianas e conversar. O horário do descanso e a chave geral vêm das opções de sandbox.',
    'Hold up a player: weapons down, hands up, a few valuable items taken, then the crew leaves. Refusing gets him shot. Inherit robs by register (raiders almost always, mercenaries about half the time) and only when the player is alone. On means this crew always tries, whatever its faction and whoever he is with.': 'Render um jogador: armas no chão, mãos para cima, alguns itens valiosos levados, e o grupo vai embora. Quem recusar leva tiro. Herdar assalta conforme o perfil do grupo (saqueadores quase sempre, mercenários cerca de metade das vezes) e só quando o jogador está sozinho. Ligado significa que este grupo sempre tenta, qualquer que seja a facção e esteja o jogador com quem estiver.',
    'ORDERS': 'ORDENS', 'Leadership and assigned stance': 'Liderança e postura designada', 'DANGER RESPONSE': 'REAÇÃO AO PERIGO',
    'Warnings, controlled retreat and escape': 'Avisos, recuo controlado e fuga', 'COMBAT MOVEMENT': 'MOVIMENTO EM COMBATE',
    'Cover, spacing and coordinated manoeuvres': 'Cobertura, espaçamento e manobras coordenadas', 'SURVIVAL & ROUTINE': 'SOBREVIVÊNCIA E ROTINA',
    'Recovery, scavenging and calm-state activity': 'Recuperação, coleta e atividades cotidianas', 'OUTLAW CONDUCT': 'CONDUTA FORA DA LEI',
    'Demands made of players at gunpoint': 'Exigências feitas aos jogadores sob a mira de uma arma',
    'Inherit': 'Herdar', 'On': 'Ligado', 'Off': 'Desligado', 'Common': 'Comum', 'Uncommon': 'Incomum', 'Rare': 'Raro', 'Very Rare': 'Muito raro', 'Unseen': 'Nunca visto',
    # module/scope editor
    '(none)': '(nenhum)', 'Custom (': 'Personalizado (', ' SPAWN OPTIONS': ' OPÇÕES DE GERAÇÃO', 'Use NPC profile': 'Usar perfil do NPC',
    'On by default': 'Ligado por padrão', 'Off by default': 'Desligado por padrão', 'Use faction': 'Usar facção', 'On for this NPC': 'Ligado para este NPC',
    'Off for this NPC': 'Desligado para este NPC',
    " Use NPC profile leaves the choice to each member's behavior profile. Individual NPC overrides take precedence.": ' Usar perfil do NPC deixa a escolha para o perfil de comportamento de cada membro. Alterações individuais de NPC têm prioridade.',
    ' Use faction follows its default, then the NPC behavior profile when the faction has no override.': ' Usar facção segue o padrão dela e, se a facção não tiver alteração, o perfil de comportamento do NPC.',
    'Overrides this module for the current scope.': 'Altera este módulo no escopo atual.',
    ' World switches and valid task conditions always apply.': ' As chaves globais e as condições válidas de tarefa sempre se aplicam.',
    'APPLY ': 'APLICAR ', ' TO FACTION': ' À FACÇÃO', 'ALLOWED': 'PERMITIDO', 'NOT SELECTED': 'NÃO SELECIONADO', 'CATALOG ERROR: ': 'ERRO NO CATÁLOGO: ',
    '  ON': '  LIGADO', 'PREVIEW VARIATION': 'PRÉVIA DE VARIAÇÃO', 'ENABLE AN OUTFIT SET TO PREVIEW': 'ATIVE UM CONJUNTO DE ROUPAS PARA VER A PRÉVIA',
    'No outfit set is enabled for spawning': 'Nenhum conjunto de roupas está ativado para geração', 'CUSTOM': 'PERSONALIZADO',
    'NATIVE ITEM COLOR': 'COR ORIGINAL DO ITEM', 'Clear slot': 'Limpar espaço',
    # attachments / item picker
    'WEAPON ATTACHMENTS': 'ACESSÓRIOS DE ARMA', 'Choose a primary or secondary firearm first.': 'Escolha primeiro uma arma de fogo principal ou secundária.',
    'CLOSE': 'FECHAR', 'Weapon choice': 'Escolha de arma', 'PAGE 1 / 1': 'PÁGINA 1 / 1', '0 ATTACHED': '0 INSTALADOS', 'PAGE ': 'PÁGINA ',
    ' ATTACHED TO THIS WEAPON': ' INSTALADOS NESTA ARMA', 'ATTACHED - CLICK TO REMOVE': 'INSTALADO - CLIQUE PARA REMOVER',
    'UNVERIFIED MOD PART': 'PEÇA DE MOD NÃO VERIFICADA', 'Only parts whose mount list names this weapon.': 'Só peças cuja lista de encaixe cita esta arma.',
    'MODDED / UNSAFE': 'DE MOD / INSEGURO', 'UNVERIFIED MOD PARTS MAY ERROR OR CRASH - USE AT YOUR OWN RISK.': 'PEÇAS DE MOD NÃO VERIFICADAS PODEM DAR ERRO OU TRAVAR O JOGO - USE POR SUA CONTA E RISCO.',
    'REMOVE ALL': 'REMOVER TUDO', 'DONE||64 , 120 ,': 'CONCLUÍDO', 'CANCEL': 'CANCELAR', 'APPLY||64 , 116 ,': 'APLICAR', 'SELECT ITEM': 'SELECIONAR ITEM',
    'Click to preview. Apply to keep.': 'Clique para ver a prévia. Aplique para manter.', 'Search item name or type...': 'Buscar nome ou tipo do item...',
    'Enable multiple options': 'Permitir várias opções', 'ACTIVE CHOICES': 'ESCOLHAS ATIVAS', 'ATTACHMENTS': 'ACESSÓRIOS', 'SELECTED 0 / 4': 'SELECIONADOS 0 / 4',
    'SELECTED ': 'SELECIONADOS ', 'COLLISION DETECTED': 'CONFLITO DETECTADO', 'ACTIVE': 'ATIVO', 'SLOT EMPTY': 'ESPAÇO VAZIO', 'NO ICON': 'SEM ÍCONE',
    # voice preview
    'LIVE': 'AO VIVO', 'DEFAULT': 'PADRÃO', 'OFFLINE DEFAULT': 'PADRÃO OFFLINE', 'PLAYER  ': 'JOGADOR  ', 'Default (': 'Padrão (',
    ' - text only': ' - só texto', 'Faction voice sample: ': 'Amostra de voz da facção: ', 'text only': 'só texto', 'Text-only personality.': 'Personalidade só em texto.',
    ' recordings + contextual text. Preview a reaction below.': ' gravações + texto contextual. Ouça a prévia de uma reação abaixo.',
    'Unknown profile - the runtime will use the roaming hostile fallback.': 'Perfil desconhecido - o jogo vai usar o padrão de hostil errante.',
    'NPC audio disabled for voice review. Text dialogue remains enabled.': 'Áudio dos NPCs desativado para revisão de voz. Os diálogos em texto continuam ativos.',
    'No lines for this reaction.': 'Nenhuma fala para esta reação.', 'AUDIO UNAVAILABLE ': 'ÁUDIO INDISPONÍVEL ', 'TEXT ': 'TEXTO ',
    ' / Custom||window . currentFactionCustom and': ' / Personalizada', ' / Built-in override': ' / Alteração do padrão', 'World: ': 'Mundo: ',
    '  /  NPC Preset': '  /  Predefinição de NPC', ' / Custom||window . currentProfileCustom and': ' / Personalizado', ' / Custom||profile . id ..': ' / Personalizado',
    'Faction: ': 'Facção: ', 'BEHAVIOR  /  ': 'COMPORTAMENTO  /  ', 'LOADOUT  /  ': 'EQUIPAMENTO  /  ', 'STATS  /  HP ': 'ATRIBUTOS  /  PV ',
    '   STR ': '   FOR ', '   AIM ': '   MIR ', ' CLEARED': ' LIMPO',
    # hair / beard
    'Clean shaven': 'Barbeado', 'Bald / no hair': 'Careca / sem cabelo', 'Not available for female body': 'Indisponível para corpo feminino',
    'Not available': 'Indisponível', 'BEARD CREATOR': 'CRIADOR DE BARBA', 'HAIR CREATOR': 'CRIADOR DE CABELO',
    'Vanilla Build 42 styles plus loaded mod styles. Select a head to apply it.': 'Estilos originais da Build 42 mais os estilos de mods carregados. Selecione uma cabeça para aplicar.',
    'Search style name...': 'Buscar nome do estilo...', 'COLOR PRESETS': 'CORES PREDEFINIDAS', 'CUSTOM COLOR': 'COR PERSONALIZADA', 'ACTIVE: ': 'ATIVO: ',
    'VANILLA NONE': 'NENHUM (ORIGINAL)',
    # folders
    'FOLDER ACTIONS': 'AÇÕES DA PASTA', 'CREATE FOLDER': 'CRIAR PASTA', 'Folder name': 'Nome da pasta',
    'Example: Raiders, Story factions, Test groups...': 'Exemplo: Saqueadores, Facções da história, Grupos de teste...', 'DELETE FOLDER': 'EXCLUIR PASTA',
    "Delete folder '": "Excluir a pasta '", "'?\nFactions stay intact and return to Unfiled.": "'?\nAs facções continuam intactas e voltam para Sem pasta.",
    'FOLDER DELETE FAILED - COULD NOT SAVE': 'FALHA AO EXCLUIR PASTA - NÃO FOI POSSÍVEL SALVAR',
    'FOLDER DELETED - FACTIONS MOVED TO UNFILED': 'PASTA EXCLUÍDA - FACÇÕES MOVIDAS PARA SEM PASTA', 'RENAME': 'RENOMEAR',
    'CREATE||existing and "RENAME" or': 'CRIAR', 'Move this folder up': 'Mover esta pasta para cima', 'Move this folder down': 'Mover esta pasta para baixo',
    'Folder actions: rename, copy or delete': 'Ações da pasta: renomear, copiar ou excluir', 'MOVING': 'MOVENDO',
    # roster ammo column
    'INFINITE': 'INFINITA', 'no limit': 'sem limite', 'melee': 'corpo a corpo', '0 MAGS': '0 CARREG.', 'dry': 'sem munição', ' MAG': ' CARREG.',
    ' MAGS': ' CARREG.', ' each': ' cada', 'capacity by weapon': 'capacidade conforme a arma', 'UNARMED': 'DESARMADO', 'NO AMMO': 'SEM MUNIÇÃO',
    'ISSUES  ': 'PROBLEMAS  ', 'MEMBER PRESETS   ': 'MEMBROS PREDEFINIDOS   ', 'Primary': 'Principal', 'Melee': 'Corpo a corpo',
    'NO NPC PRESET': 'SEM PREDEFINIÇÃO DE NPC', 'Select or create a member': 'Selecione ou crie um membro',
    # validation
    'Game day': 'Dia de jogo', 'Lone size': 'Tamanho solo', 'Group size': 'Tamanho do grupo',
    ': enter whole numbers in the shown range.': ': digite números inteiros dentro do intervalo mostrado.',
    ': maximum must be at least the minimum.': ': o máximo precisa ser pelo menos igual ao mínimo.', 'Support size': 'Tamanho do apoio',
    'Support calls': 'Chamadas de apoio', 'Spawn weight': 'Peso de geração', 'Lone weight': 'Peso solo', 'Group weight': 'Peso de grupo',
    ': use ': ': use de ', ' to ': ' a ',
    # save / import / export
    '  /  CUSTOM': '  /  PERSONALIZADA', 'SAVED': 'SALVO', 'Could not save faction. Your edits are still open.': 'Não foi possível salvar a facção. Suas edições continuam abertas.',
    ' (Copy)': ' (Cópia)', 'FACTION DELETE FAILED - COULD NOT SAVE': 'FALHA AO EXCLUIR FACÇÃO - NÃO FOI POSSÍVEL SALVAR',
    'FACTION AND ITS NPC PRESETS REMOVED': 'FACÇÃO E SUAS PREDEFINIÇÕES DE NPC REMOVIDAS', 'SELECT A FACTION TO EXPORT': 'SELECIONE UMA FACÇÃO PARA EXPORTAR',
    'EXPORT FAILED: ': 'FALHA AO EXPORTAR: ', 'CODE COPIED - ': 'CÓDIGO COPIADO - ', ' NPCS - ': ' NPCS - ', ' KB - PASTE IT ON DISCORD': ' KB - COLE NO DISCORD',
    'TOO LONG TO COPY - CODE SAVED TO ZOMBOID/LUA/ALIFE_FACTION_CODE.TXT': 'LONGO DEMAIS PARA COPIAR - CÓDIGO SALVO EM ZOMBOID/LUA/ALIFE_FACTION_CODE.TXT',
    'EXPORT FAILED: CODE COULD NOT BE COPIED OR SAVED': 'FALHA AO EXPORTAR: NÃO FOI POSSÍVEL COPIAR NEM SALVAR O CÓDIGO',
    'NO CODE COPIED  -  COPY A SHARE CODE FIRST': 'NENHUM CÓDIGO COPIADO  -  COPIE UM CÓDIGO DE COMPARTILHAMENTO PRIMEIRO',
    'IMPORT FAILED: ': 'FALHA AO IMPORTAR: ', 'IMPORT CANCELLED': 'IMPORTAÇÃO CANCELADA', 'MISSING ITEMS - ': 'ITENS FALTANDO - ',
    ' - FULL LIST IN CONSOLE.TXT': ' - LISTA COMPLETA NO CONSOLE.TXT', 'IMPORT FAILED: FACTION COULD NOT BE SAVED': 'FALHA AO IMPORTAR: NÃO FOI POSSÍVEL SALVAR A FACÇÃO',
    'IMPORT PARTIAL: FACTION ADDED, NPCS FAILED': 'IMPORTAÇÃO PARCIAL: FACÇÃO ADICIONADA, NPCS FALHARAM', 'FACTION PACK IMPORTED - ': 'PACOTE DE FACÇÃO IMPORTADO - ',
    ' NPCS': ' NPCS', ' ITEMS MISSING': ' ITENS FALTANDO', 'Could not save NPC. Your edits are still open.': 'Não foi possível salvar o NPC. Suas edições continuam abertas.',
    'Delete this NPC?': 'Excluir este NPC?', 'Delete this faction and all its NPC presets?': 'Excluir esta facção e todas as suas predefinições de NPC?',
    'SYNCING CREATOR TO SERVER...': 'SINCRONIZANDO O CRIADOR COM O SERVIDOR...',
    'SAVED LOCALLY -- APPLIES WHEN YOU START OR HOST A WORLD': 'SALVO LOCALMENTE -- VALE QUANDO VOCÊ INICIAR OU HOSPEDAR UM MUNDO',
    'APPLIED ': 'APLICADO: ', ' TO ALL MEMBERS': ' A TODOS OS MEMBROS',
    # combat page
    'Primary firearm': 'Arma de fogo principal', 'Secondary firearm': 'Arma de fogo secundária', 'Melee weapon': 'Arma corpo a corpo',
    'Click to edit ': 'Clique para editar ', '. Right-click to clear.': '. Clique direito para limpar.', 'Health (HP)': 'Vida (PV)', 'Strength': 'Força',
    'Endurance': 'Resistência', 'Awareness': 'Percepção', 'Aiming||10 } , {': 'Pontaria', 'VITALITY & SKILLS': 'VITALIDADE E HABILIDADES',
    'Exact starting HP, 1-200. Default: 50 HP. Other skills use 1-10 ratings.': 'PV inicial exato, 1-200. Padrão: 50 PV. As outras habilidades usam notas de 1 a 10.',
    'None||dropOptions = { {': 'Nenhuma', 'Very Low': 'Muito baixa', 'Low': 'Baixa', 'Moderate': 'Moderada', 'High': 'Alta', 'Very High': 'Muito alta',
    'Always': 'Sempre', 'DAMAGE': 'DANO', 'Weapon damage dealt (%)': 'Dano causado pela arma (%)', 'Incoming damage blocked (%)': 'Dano recebido bloqueado (%)',
    "Multiplies the weapon's damage: 25% = one quarter, 100% = normal, 200% = double.": 'Multiplica o dano da arma: 25% = um quarto, 100% = normal, 200% = o dobro.',
    'Reduces incoming damage. At 25%, the NPC takes 75% of the hit. Maximum reduction: 90%.': 'Reduz o dano recebido. Com 25%, o NPC sofre 75% do golpe. Redução máxima: 90%.',
    'LOOT': 'SAQUE', 'Weapon drop chance': 'Chance de largar a arma', 'Armor drop chance': 'Chance de largar a armadura', 'Weapon condition': 'Estado da arma',
    'Armor condition': 'Estado da armadura',
    'Loot after death, not the chance to spawn armed. Choose weapons in Loadout. Each NPC gets a stable chance within the range. Always (100%) keeps issued weapons; Off removes them. Does not create missing weapons or control magazine drops.': 'Saque após a morte, não a chance de surgir armado. Escolha as armas em Equipamento. Cada NPC recebe uma chance fixa dentro do intervalo. Sempre (100%) mantém as armas distribuídas; Desligado as remove. Não cria armas que faltam nem controla a queda de carregadores.',
    'None 0% / Very Low 5% / Low 20% / Moderate 50% / High 75% / Very High 90% / Always 100%. Existing custom percentages are preserved.': 'Nenhuma 0% / Muito baixa 5% / Baixa 20% / Moderada 50% / Alta 75% / Muito alta 90% / Sempre 100%. Porcentagens personalizadas existentes são mantidas.',
    'COMBAT SUPPORT': 'APOIO DE COMBATE', 'Calling permission': 'Permissão para chamar', 'Use faction setting': 'Usar configuração da facção',
    'Everyone / allow this NPC': 'Todos / permitir este NPC', 'Disabled': 'Desativado', 'Delivery': 'Chegada', 'Use faction delivery': 'Usar chegada da facção',
    'Ground vehicle': 'Veículo terrestre', 'Helicopter': 'Helicóptero', 'Ground / helicopter': 'Terrestre / helicóptero', 'Helicopter role': 'Função do helicóptero',
    'Use faction role': 'Usar função da facção', 'No helicopter': 'Sem helicóptero', 'Squad insertion': 'Inserção de esquadrão', 'Spotlight': 'Holofote',
    'Use faction + assigned role preserves the faction policy. Yes gives this member radio-calling ability without replacing its combat specialist. Admin spawn overrides still take precedence.': 'Usar facção + função designada mantém a política da facção. Sim dá a este membro a capacidade de chamar pelo rádio sem substituir o especialista de combate dele. Alterações de geração do admin ainda têm prioridade.',
    'Spotlight needs Helicopter or Ground / helicopter delivery. The combined setting brings a ground squad and the light; Helicopter alone brings only the light. With Squad insertion, the combined setting chooses either delivery per call.': 'Holofote precisa de chegada por Helicóptero ou Terrestre / helicóptero. A opção combinada traz um esquadrão terrestre e a luz; Helicóptero sozinho traz só a luz. Com Inserção de esquadrão, a opção combinada escolhe um dos dois tipos de chegada a cada chamada.',
    'Defaults: Faction settings > Support': 'Padrões: Configurações da facção > Apoio', 'This NPC cannot request backup.': 'Este NPC não pode pedir reforços.',
    'Squad size and backup faction use faction settings.': 'O tamanho do esquadrão e a facção de reforço usam as configurações da facção.',
    '%02d:00 - %02d:00 (saved schedule)': '%02d:00 - %02d:00 (horário salvo)', 'to': 'a',
    # spawn policy
    'SPAWN POLICY': 'REGRAS DE GERAÇÃO', 'Enable natural spawning': 'Ativar geração natural', 'Player disposition': 'Atitude com o jogador',
    'Friendly and neutral factions can appear naturally. Scouts, ambushes and raids require a hostile faction.': 'Facções amigáveis e neutras podem aparecer naturalmente. Batedores, emboscadas e invasões exigem uma facção hostil.',
    'Relative faction selection weight, not a percentage. Zero disables natural spawning. Sandbox settings control overall encounter frequency.': 'Peso relativo na escolha da facção, não uma porcentagem. Zero desativa a geração natural. As opções de sandbox controlam a frequência geral de encontros.',
    'WHEN': 'QUANDO', 'Inclusive last day. Day 0 is the first day. Use 3650 for a long-running faction.': 'Último dia, inclusive. O dia 0 é o primeiro dia. Use 3650 para uma facção que dure muito.',
    'Active hours': 'Horário ativo', 'All day (00:00 - 24:00)': 'O dia todo (00:00 - 24:00)', 'Dawn (05:00 - 08:00)': 'Madrugada (05:00 - 08:00)',
    'Morning (08:00 - 12:00)': 'Manhã (08:00 - 12:00)', 'Midday (12:00 - 14:00)': 'Meio-dia (12:00 - 14:00)', 'Afternoon (14:00 - 18:00)': 'Tarde (14:00 - 18:00)',
    'Evening (18:00 - 22:00)': 'Noitinha (18:00 - 22:00)', 'Night (22:00 - 05:00)': 'Noite (22:00 - 05:00)', 'Daytime (06:00 - 18:00)': 'Diurno (06:00 - 18:00)',
    'Nighttime (18:00 - 06:00)': 'Noturno (18:00 - 06:00)',
    'When new encounters may begin. Existing squads finish their tasks; they do not disappear at the end of this window.': 'Quando novos encontros podem começar. Esquadrões existentes terminam suas tarefas; eles não somem no fim desse período.',
    'PARTY SIZE': 'TAMANHO DO GRUPO', 'Lone survivors + groups': 'Solitários + grupos', 'Lone survivors only': 'Só solitários', 'Groups only': 'Só grupos',
    'Lone size (1-3)': 'Tamanho solo (1-3)', 'Group size (4-32)': 'Tamanho do grupo (4-32)',
    'Relative weight. Blank uses sandbox defaults; zero disables this party type.': 'Peso relativo. Em branco usa os padrões do sandbox; zero desativa este tipo de grupo.',
    'Placement distance is managed by A-Life.': 'A distância de posicionamento é controlada pelo A-Life.', 'ALLOWED ENCOUNTERS': 'ENCONTROS PERMITIDOS',
    'ROAMING': 'ERRANTES', 'RESIDENTS': 'MORADORES', 'ALL||} } , {': 'TODOS', 'NONE': 'NENHUM', 'any kind of outpost': 'qualquer tipo de posto avançado',
    ' of ': ' de ', ' outpost kinds': ' tipos de posto avançado', 'None selected - no natural encounters': 'Nada selecionado - sem encontros naturais',
    ' selected  /  ': ' selecionados  /  ', '  /  events still follow sandbox triggers': '  /  eventos ainda seguem os gatilhos do sandbox',
    'POLICY': 'REGRAS', 'ENCOUNTERS': 'ENCONTROS', 'LOCATION': 'LOCAL', 'WHERE': 'ONDE', 'Anywhere': 'Qualquer lugar', 'Selected towns': 'Cidades selecionadas',
    'Wilderness only': 'Só áreas selvagens', 'Roads & highways': 'Estradas e rodovias', 'Specific building types': 'Tipos específicos de prédio',
    'Include wilderness with selected towns': 'Incluir áreas selvagens junto com as cidades selecionadas', 'All towns': 'Todas as cidades',
    'All registered towns, including towns added later. Untick to choose individual towns below.': 'Todas as cidades registradas, incluindo as adicionadas depois. Desmarque para escolher cidades individuais abaixo.',
    'Same faction': 'Mesma facção',
    # support defaults
    'SUPPORT DEFAULTS': 'PADRÕES DE APOIO', 'Who calls, how they arrive, and whether a night helicopter also searches the contact.': 'Quem chama, como chegam e se um helicóptero noturno também procura o contato.',
    'Who can call backup?': 'Quem pode chamar reforços?', 'Everyone': 'Todos',
    "Radio operator: only the squad's radio operator can call. Everyone: any member may call. Disabled: no faction calls. The shared squad cooldown and call limit prevent repeated calls; NPC overrides still apply.": 'Operador de rádio: só o operador de rádio do esquadrão pode chamar. Todos: qualquer membro pode chamar. Desativado: a facção não chama. A recarga e o limite de chamadas compartilhados do esquadrão evitam chamadas repetidas; alterações de NPC ainda se aplicam.',
    'How does support arrive?': 'Como o apoio chega?', 'Car pull-up (sound + squad)': 'Carro chegando (som + esquadrão)',
    'None||"Helicopter role" , { {': 'Nenhuma', 'Support - rappel troops': 'Apoio - tropas de rapel', 'Spotlight - night / outdoors': 'Holofote - noite / ao ar livre',
    'Helicopter + spotlight + troops': 'Helicóptero + holofote + tropas', 'Pull-up sound (no vehicle is spawned)': 'Som de chegada (nenhum veículo é gerado)',
    'Automatic': 'Automático', 'Pickup truck': 'Picape', 'Pickup van': 'Furgão', 'Passenger van': 'Van de passageiros', 'Police car': 'Viatura de polícia',
    'NPCs per call (1-8)': 'NPCs por chamada (1-8)', 'Calls per squad (0-10)': 'Chamadas por esquadrão (0-10)',
    "Maximum lifetime calls for the calling squad; zero disables requests. The world's call cap, cooldown and active-NPC budget may reduce this number. Reinforcements cannot call more reinforcements.": 'Máximo de chamadas durante toda a vida do esquadrão; zero desativa os pedidos. O limite global de chamadas, a recarga e o limite de NPCs ativos podem reduzir esse número. Reforços não podem chamar mais reforços.',
    'BACKUP FACTIONS': 'FACÇÕES DE REFORÇO', 'Call ': 'Chamada ',
    "Uses this faction for this call, not a random pool. Another faction must be friendly or allied in at least one direction; otherwise backup uses the caller's own faction. Calls after the third use the same faction.": 'Usa esta facção nesta chamada, em vez de um sorteio. Outra facção precisa ser amigável ou aliada em pelo menos um sentido; senão o reforço vem da própria facção de quem chamou. Chamadas depois da terceira usam a mesma facção.',
    'Add backup choices: set factions Friendly / Allied in Relations.': 'Para ter opções de reforço, marque facções como Amigável / Aliado em Relações.',
    'Disabled by default; NPC overrides may allow calls.': 'Desativado por padrão; alterações de NPC podem permitir chamadas.',
    'Car sound + distant squad; radio position updates for five seconds.': 'Som de carro + esquadrão distante; a posição pelo rádio atualiza por cinco segundos.',
    'No helicopter role: backup falls back to ground.': 'Sem função de helicóptero: o reforço vem por terra.',
    'Ground squad + night/outdoor searchlight.': 'Esquadrão terrestre + holofote noturno/ao ar livre.',
    'Night/outdoor searchlight reports to the calling squad; no troops.': 'O holofote noturno/ao ar livre informa o esquadrão que chamou; sem tropas.',
    'Helicopter insertion plus a spotlight on the same identified outdoor target at night.': 'Inserção por helicóptero mais um holofote no mesmo alvo identificado ao ar livre, à noite.',
    'Ground or helicopter squad, chosen per call.': 'Esquadrão terrestre ou de helicóptero, escolhido a cada chamada.',
    'Helicopter squad insertion; world limits still apply.': 'Inserção de esquadrão por helicóptero; os limites globais ainda se aplicam.',
    # layers / tabs / roster
    'OUTFIT': 'ROUPA', 'ARMOR': 'ARMADURA', 'LAYERS': 'CAMADAS', 'MAKEUP': 'MAQUIAGEM', 'FACTIONS': 'FACÇÕES', 'MEMBERS': 'MEMBROS',
    'EDITOR + MODEL': 'EDITOR + MODELO', 'FACTION LIST': 'LISTA DE FACÇÕES', 'Search factions...': 'Buscar facções...', '+ NEW': '+ NOVA',
    'Create a new faction': 'Criar uma nova facção', 'NEW FOLDER': 'NOVA PASTA', '+ NEW FACTION': '+ NOVA FACÇÃO', 'OPEN SETTINGS': 'ABRIR CONFIGURAÇÕES',
    'COPY CODE': 'COPIAR CÓDIGO', 'LOAD CODE': 'CARREGAR CÓDIGO',
    'Copies this faction and all its NPCs as one share code. Paste it on Discord. Also saved to Zomboid/Lua/alife_faction_code.txt as a backup.': 'Copia esta facção e todos os seus NPCs como um único código de compartilhamento. Cole no Discord. Também é salvo em Zomboid/Lua/alife_faction_code.txt como backup.',
    'Copy a share code, then click: it is added as a new faction. With no code copied, loads Zomboid/Lua/alife_faction_code.txt.': 'Copie um código de compartilhamento e clique: ele é adicionado como uma nova facção. Sem nenhum código copiado, carrega Zomboid/Lua/alife_faction_code.txt.',
    'DUPLICATE FACTION': 'DUPLICAR FACÇÃO', 'DELETE': 'EXCLUIR', 'Select a faction': 'Selecione uma facção', 'none': 'nenhum', 'INHERITED MODULES': 'MÓDULOS HERDADOS',
    'DEFAULT PROGRAM': 'PROGRAMA PADRÃO', 'NATURAL PARTIES': 'GRUPOS NATURAIS', 'Lone survivors: 1-3': 'Solitários: 1-3', 'Groups: ': 'Grupos: ',
    'Lone 1-3 / Groups ': 'Solitários 1-3 / Grupos ', 'MEMBER PRESETS   0': 'MEMBROS PREDEFINIDOS   0', 'SELECT A FACTION': 'SELECIONE UMA FACÇÃO',
    'Search members...': 'Buscar membros...', '+ NEW MEMBER': '+ NOVO MEMBRO', 'ALL||{ { "all" ,': 'TODOS', 'RANGED': 'À DISTÂNCIA', 'MELEE': 'CORPO A CORPO',
    'ISSUES': 'PROBLEMAS', 'MEMBER': 'MEMBRO', 'BEHAVIOR': 'COMPORT.', 'WEAPON': 'ARMA', 'AMMO': 'MUNIÇÃO', 'WT': 'PESO', 'STATUS': 'SITUAÇÃO',
    'NO LOADOUT ISSUES': 'SEM PROBLEMAS DE EQUIPAMENTO', 'NO MEMBERS MATCH THIS VIEW': 'NENHUM MEMBRO CORRESPONDE A ESTE FILTRO', 'DUPLICATE NPC': 'DUPLICAR NPC',
    'Faction / NPC Preset': 'Facção / Predefinição de NPC', 'NO MEMBER SELECTED': 'NENHUM MEMBRO SELECIONADO',
    'Choose a preset from the roster, or create a new member for this faction.': 'Escolha uma predefinição da lista ou crie um novo membro para esta facção.',
    'Create a member in the currently selected faction.': 'Criar um membro na facção selecionada.',
    'Previous member - saves pending edits first.': 'Membro anterior - salva as edições pendentes antes.',
    'Next member - keep faction settings open while previewing the roster.': 'Próximo membro - mantém as configurações da facção abertas enquanto você percorre a lista.',
    # identity page
    'Faction: -': 'Facção: -', 'WHO IS THIS NPC?': 'QUEM É ESTE NPC?', 'Readable identity first; internal IDs stay out of the way.': 'Identidade legível primeiro; IDs internos ficam fora do caminho.',
    'TAG & SPAWN': 'TAG E GERAÇÃO', "Tag describes the member's job. Spawn Weight In Group controls how often this preset is selected.": 'A tag descreve a função do membro. Peso de geração no grupo controla com que frequência esta predefinição é escolhida.',
    'DISCOVERY & ADMIN NOTES': 'BUSCA E NOTAS DO ADMIN', 'Tags improve filtering. Notes are private creator metadata.': 'Tags ajudam na filtragem. As notas são metadados privados do criador.',
    'Display name': 'Nome exibido', 'Gender': 'Gênero', 'Tag': 'Tag', 'Spawn Weight In Group': 'Peso de geração no grupo',
    'How often this preset is selected within its faction. Common is the normal rate; Rare and Very Rare keep specialists from taking over a squad.': 'Com que frequência esta predefinição é escolhida dentro da facção. Comum é a taxa normal; Raro e Muito raro evitam que especialistas dominem um esquadrão.',
    'Filter tags': 'Tags de filtro', 'outdoor, rifle, medic, trader': 'ao ar livre, rifle, médico, comerciante', 'Notes': 'Notas',
    # appearance page
    'CHARACTER APPEARANCE': 'APARÊNCIA DO PERSONAGEM', 'Skin tone': 'Tom de pele', 'Hair': 'Cabelo', 'CHOOSE HAIR': 'ESCOLHER CABELO', 'Beard': 'Barba',
    'CHOOSE BEARD': 'ESCOLHER BARBA', 'OUTFIT SETS': 'CONJUNTOS DE ROUPA', 'Enable this set for spawning': 'Ativar este conjunto para geração',
    'Keep up to four random spawn options per clothing slot. Off: the next click replaces the slot.': 'Manter até quatro opções aleatórias de geração por espaço de roupa. Desligado: o próximo clique substitui o espaço.',
    'Cycles only through outfit sets marked Enable this set for spawning. A random pool choice is shown each time.': 'Percorre só os conjuntos marcados com Ativar este conjunto para geração. A cada vez é mostrada uma escolha aleatória.',
    'BODY SLOTS': 'ESPAÇOS DO CORPO', 'Open the icon catalog for ': 'Abrir o catálogo de ícones de ', '. Select up to four spawn choices.': '. Selecione até quatro opções de geração.',
    'TOP COLOR: NATIVE ITEM COLOR': 'COR DA PARTE DE CIMA: COR ORIGINAL DO ITEM', 'NATIVE': 'ORIGINAL',
    'Keep the authored color of the selected clothing item. It stays stable across preview refreshes.': 'Manter a cor original da peça de roupa selecionada. Ela não muda quando a prévia é atualizada.',
    'Apply this exact color to the selected clothing slot.': 'Aplicar exatamente esta cor ao espaço de roupa selecionado.',
    'Open the full color picker for the selected clothing slot.': 'Abrir o seletor de cores completo para o espaço de roupa selecionado.',
    'FACES': 'ROSTOS', 'MODDED FACE OVERLAYS': 'CAMADAS DE ROSTO DE MODS', 'Optional compatibility layer': 'Camada opcional de compatibilidade',
    'Compatible overlays appear here only when their source mod is enabled.': 'Camadas compatíveis só aparecem aqui quando o mod de origem está ativado.',
    'FACE OVERLAY': 'CAMADA DE ROSTO', 'Face overlays': 'Camadas de rosto',
    'Choose a compatible modded face overlay. This does not replace the vanilla face model.': 'Escolha uma camada de rosto compatível vinda de mod. Isso não substitui o modelo de rosto original.',
    # loadout page
    'LOADOUT': 'EQUIPAMENTO', 'Keep up to four random spawn options per weapon slot. Off: the next click replaces the slot.': 'Manter até quatro opções aleatórias de geração por espaço de arma. Desligado: o próximo clique substitui o espaço.',
    'PRIMARY': 'PRINCIPAL', 'Main weapon carried in hand.': 'Arma principal levada na mão.', 'SIDEARM': 'SECUNDÁRIA',
    'Backup firearm available when the primary is unsuitable.': 'Arma de fogo reserva, usada quando a principal não serve.', 'MELEE / BELT': 'CORPO A CORPO / CINTO',
    'Close-range fallback carried on the belt or back.': 'Alternativa de curto alcance levada no cinto ou nas costas.',
    ' Click to open the full vanilla and modded icon catalog. Right-click to clear this slot.': ' Clique para abrir o catálogo completo de ícones do jogo e de mods. Clique direito para limpar este espaço.',
    'AMMUNITION': 'MUNIÇÃO', 'Counts are complete magazines, tubes or cylinders - not loose rounds.': 'A contagem é de carregadores, tubos ou tambores completos - não de balas soltas.',
    'Primary magazines': 'Carregadores da principal', 'Sidearm magazines': 'Carregadores da secundária', 'Infinite ammunition': 'Munição infinita',
    'Unlimited combat reloads. Death loot still rolls once per authored magazine below.': 'Recargas ilimitadas em combate. O saque após a morte ainda é sorteado uma vez por carregador definido abaixo.',
    'Drop magazines on death': 'Largar carregadores ao morrer', 'Magazine drop chance (%)': 'Chance de largar carregador (%)',
    'One independent roll per primary/sidearm magazine. Three magazines at 20% means three rolls, even with infinite ammo. Fixed magazines drop loose rounds.': 'Um sorteio independente por carregador da principal/secundária. Três carregadores a 20% significam três sorteios, mesmo com munição infinita. Carregadores fixos largam balas soltas.',
    'FIREARM ATTACHMENTS': 'ACESSÓRIOS DE ARMA DE FOGO',
    'Configure compatible scopes, sights, slings, recoil pads and other parts for the selected firearms.': 'Configure lunetas, miras, bandoleiras, amortecedores de coice e outras peças compatíveis para as armas de fogo selecionadas.',
    ' each | ': ' cada | ',
    # behavior page
    'BEHAVIOR & VOICE': 'COMPORTAMENTO E VOZ', 'Behavior profile': 'Perfil de comportamento',
    'Selects the complete baseline behavior package: priorities, engagement style and allowed abilities.': 'Escolhe o pacote completo de comportamento base: prioridades, estilo de combate e habilidades permitidas.',
    'Primary doctrine': 'Doutrina principal', 'Assigns one specialist doctrine. Use Modules for smaller per-NPC exceptions.': 'Define uma doutrina de especialista. Use Módulos para exceções menores por NPC.',
    'Combat ready': 'Pronto para combate', 'Controls whether the NPC initially appears armed and prepared. Mixed follows the authored loadout pool.': 'Controla se o NPC aparece já armado e preparado. Misto segue o conjunto de equipamento definido.',
    'Select a behavior profile to see exactly what it does.': 'Selecione um perfil de comportamento para ver exatamente o que ele faz.', 'VOICE PROFILE': 'PERFIL DE VOZ', 'Profile': 'Perfil',
    'Chooses the voice pack used for warnings, combat reactions and death sounds.': 'Escolhe o pacote de voz usado em avisos, reações de combate e sons de morte.', 'Reaction': 'Reação',
    'Select the reaction category used by Play voice preview. It does not change combat behavior.': 'Escolha a categoria de reação usada no teste de voz. Não muda o comportamento em combate.',
    'PLAYTEST VOICE': 'TESTAR VOZ', 'Select a voice and reaction to preview.': 'Selecione uma voz e uma reação para ouvir.', 'NPC ABILITIES': 'HABILIDADES DO NPC',
    'Hover a setting or its info icon for a plain-language explanation.': 'Passe o mouse sobre uma opção ou o ícone de informação para ver uma explicação simples.',
    'INHERIT = USE FACTION SETTING | ON/OFF = THIS NPC ONLY': 'HERDAR = USAR CONFIG. DA FACÇÃO | LIGADO/DESLIGADO = SÓ ESTE NPC',
    'RESET ALL TO INHERIT': 'VOLTAR TUDO PARA HERDAR', 'APPLY ABILITIES TO FACTION': 'APLICAR HABILIDADES À FACÇÃO',
    # model preview
    'LIVE CHARACTER': 'PERSONAGEM AO VIVO', 'ANIMATION': 'ANIMAÇÃO', 'IN HAND': 'NA MÃO', 'Empty': 'Vazio', 'Idle': 'Parado', 'Walking': 'Andando',
    'Running': 'Correndo', 'Sprinting': 'Disparando', 'Aiming||"sprint" } , {': 'Mirando', 'Crouching': 'Agachado', 'Hands up': 'Mãos para cima', 'MODEL': 'MODELO',
    'Saved': 'Salvo', 'SAVE NOW': 'SALVAR AGORA', 'Save current faction and NPC edits now. Shortcut: Ctrl + S.': 'Salvar agora as edições atuais da facção e do NPC. Atalho: Ctrl + S.',
    # faction settings
    'FACTION SETTINGS': 'CONFIGURAÇÕES DA FACÇÃO', 'CHARACTER': 'PERSONAGEM', 'IDENTITY': 'IDENTIDADE', 'RELATIONS': 'RELAÇÕES', 'SPAWNING': 'GERAÇÃO',
    'BEHAVIOR DEFAULTS': 'COMPORTAMENTO PADRÃO', 'SUPPORT': 'APOIO', 'FACTION IDENTITY': 'IDENTIDADE DA FACÇÃO', 'Faction name': 'Nome da facção',
    'Category': 'Categoria', 'Description': 'Descrição', 'Unknown faction disposition': 'Atitude com facções desconhecidas', 'SET UP SPAWNING': 'CONFIGURAR GERAÇÃO',
    'SET UP SUPPORT': 'CONFIGURAR APOIO', 'RELATIONS TO OTHER FACTIONS': 'RELAÇÕES COM OUTRAS FACÇÕES', 'PLAYER  -': 'JOGADOR  -', 'REFRESH LIVE': 'ATUALIZAR AO VIVO',
    'Search faction name...': 'Buscar nome da facção...', 'NPC overrides win; world switches still apply.': 'Alterações de NPC têm prioridade; as chaves globais ainda se aplicam.',
    "USE EACH NPC'S PROFILE DEFAULTS": 'USAR OS PADRÕES DO PERFIL DE CADA NPC', 'EXTERNAL MODULE OVERRIDES': 'ALTERAÇÕES DE MÓDULOS EXTERNOS',
    'Core AI stays active. Assign a loaded custom module ID only when a separate module provides one.': 'A IA principal continua ativa. Só defina o ID de um módulo personalizado carregado quando um módulo separado o fornecer.',
    'No custom override': 'Sem alteração personalizada', 'NOT ASSIGNED': 'NÃO DEFINIDO', 'CHANGES SAVE AUTOMATICALLY': 'AS ALTERAÇÕES SÃO SALVAS AUTOMATICAMENTE',
    'SYSTEMS & MODULES': 'SISTEMAS E MÓDULOS', 'Built-in systems and optional integrations - not a live health report': 'Sistemas embutidos e integrações opcionais - não é um relatório de saúde ao vivo',
    'NPC BRAIN': 'CÉREBRO DO NPC', 'Decision tree / persistent task queue': 'Árvore de decisão / fila de tarefas persistente', 'PERCEPTION': 'PERCEPÇÃO',
    'Targets, memory, hearing and threat scoring': 'Alvos, memória, audição e avaliação de ameaças', 'MOVEMENT': 'MOVIMENTO',
    'Pathing, vaulting, formation and recovery': 'Rotas, pulos de obstáculos, formação e recuperação', 'COMBAT': 'COMBATE',
    'Aiming, melee, suppression and retreat': 'Mira, corpo a corpo, supressão e recuo', 'SCAVENGING': 'COLETA',
    'World search, reservations and inventory': 'Busca no mundo, reservas e inventário', 'VOICE': 'VOZ', 'Speech, combat barks and death sounds': 'Fala, gritos de combate e sons de morte',
    'ENCOUNTER': 'ENCONTRO', 'Group placement and encounter startup': 'Posicionamento de grupos e início de encontros', 'FULL RAID': 'INVASÃO TOTAL',
    'Raid waves, staging and persistence': 'Ondas da invasão, preparação e persistência', 'BUILT-IN': 'EMBUTIDO', 'OVERRIDE SET': 'ALTERAÇÃO DEFINIDA',
    'ENCOUNTER CATALOG': 'CATÁLOGO DE ENCONTROS',
    'Exact runtime rules: chance, squad size, location, time, placement, scene and AI profile.': 'Regras exatas em jogo: chance, tamanho do esquadrão, local, horário, posicionamento, cena e perfil de IA.',
    ' TEMPLATES | ': ' MODELOS | ', ' RANDOM WEIGHT': ' PESO ALEATÓRIO', 'DISABLED': 'DESATIVADO', 'FILTERED BY DEBUG OVERRIDE': 'FILTRADO POR ALTERAÇÃO DE DEPURAÇÃO',
    'WEIGHT %d | %.1f%% OF RANDOM ROLLS': 'PESO %d | %.1f%% DOS SORTEIOS', 'SQUAD': 'ESQUADRÃO', ' NPCs | ': ' NPCs | ', 'ANY TIME': 'QUALQUER HORA',
    'ANYWHERE': 'QUALQUER LUGAR', 'PLACEMENT & AI': 'POSICIONAMENTO E IA', 'RING': 'ANEL', ' | SCENE ': ' | CENA ', 'STANCE ': 'POSTURA ', 'PERSISTENT': 'PERSISTENTE',
    'AWARENESS ': 'PERCEPÇÃO ', 'STANDARD LIFECYCLE': 'CICLO DE VIDA PADRÃO',
    # window chrome
    'PROJECT A-LIFE CREATOR': 'CRIADOR DO PROJECT A-LIFE', 'no faction': 'sem facção', 'no NPC picked': 'nenhum NPC escolhido', 'DROP ON A FOLDER': 'SOLTE NUMA PASTA',
    'MOVE TO UNFILED': 'MOVER PARA SEM PASTA', 'MOVE TO ': 'MOVER PARA ', 'REORDER FOLDER': 'REORDENAR PASTA', 'NPC SETTINGS': 'CONFIGURAÇÕES DO NPC',
    'CATALOG LOADING': 'CARREGANDO CATÁLOGO', 'SYNC TO SERVER': 'SINCRONIZAR COM O SERVIDOR', 'UNSAVED  -  AUTOSAVING': 'NÃO SALVO  -  SALVANDO AUTOMATICAMENTE',
    'SERVER SYNC COMPLETE': 'SINCRONIZAÇÃO COM O SERVIDOR CONCLUÍDA', 'SERVER SYNC FAILED: ': 'FALHA NA SINCRONIZAÇÃO: ', 'unknown': 'desconhecido',
    'Project A-Life Creator': 'Criador do Project A-Life', 'Factions & NPC settings': 'Configurações de facções e NPCs',
},
}
