# PT-BR translations, batch 1: smaller UI/data files.
# Key "en" applies to every anchored entry with that English text in the file;
# key "en||ctx-suffix" targets a single anchor when the same text needs different wording.
PT = {
'ALifeModuleCareful.lua': {'Careful relation': 'Relação cautelosa'},
'ALifeModuleCover.lua': {'Use cover': 'Usar cobertura'},
'ALifeModuleFlanking.lua': {'Ranged flanking': 'Flanqueio à distância'},
'ALifeModuleFortify.lua': {'Fortify the building': 'Fortificar o prédio'},
'ALifeModuleGunner.lua': {'Gunner (suppression fire)': 'Metralhador (fogo de supressão)'},
'ALifeModuleHealing.lua': {'Dress wounds': 'Tratar ferimentos'},
'ALifeModuleIdleLife.lua': {'Idle life': 'Vida cotidiana'},
'ALifeModuleLeader.lua': {'Squad leader': 'Líder de esquadrão'},
'ALifeModuleNightHold.lua': {'Hold the house at night': 'Defender a casa à noite'},
'ALifeModulePanic.lua': {'Panic on contact': 'Pânico ao contato'},
'ALifeModulePatrolRest.lua': {'Patrol rest': 'Descanso da patrulha'},
'ALifeModuleRadioman.lua': {'Radio call': 'Chamada de rádio'},
'ALifeModuleStances.lua': {'Encounter stance': 'Postura no encontro'},
'ALifeModuleStrafe.lua': {'Aimed movement': 'Movimento mirando'},
'ALifeModuleTalkPresence.lua': {'Talk and presence': 'Conversa e presença'},
'ALifeModuleWithdraw.lua': {'Withdraw and re-engage': 'Recuar e voltar ao combate'},
'ALifeModuleBreach.lua': {'Door-stack': 'Formação na porta', 'CQB sweep': 'Varredura em ambiente fechado'},
'ALifeModuleTravel.lua': {'Follow orders': 'Seguir ordens', 'Investigate noises': 'Investigar ruídos',
    'Regroup': 'Reagrupar', 'Group march': 'Marcha em grupo'},
'ALifeBehaviorProfiles.lua': {'Roaming hostile (Scout)': 'Hostil errante (Batedor)', 'Area patrol': 'Patrulha de área',
    'Scavenger': 'Catador', 'Squad member': 'Membro de esquadrão', 'Manhunt': 'Caçada humana'},
'ALifeModuleConducts.lua': {'Stealth killer': 'Assassino furtivo', 'Sniper': 'Atirador de elite', 'Medic': 'Médico',
    'Ambusher': 'Emboscador', 'Combat strafing (weave)': 'Movimento evasivo em combate', 'Spread out': 'Espalhar-se'},
'ALifeCreatorFolders.lua': {'New Folder': 'Nova pasta', 'ALife Law Enforcement': 'ALife Forças da Lei',
    'ALife Government': 'ALife Governo', 'ALife Families': 'ALife Famílias', 'ALife Businesses': 'ALife Comércios',
    'ALife Lone Survivors': 'ALife Sobreviventes Solitários', 'ALife Outlaws': 'ALife Foras da Lei'},
'ALifeOutpostPresets.lua': {'Fortified station': 'Delegacia fortificada', 'Held house': 'Casa ocupada',
    'Fortified field base': 'Base de campo fortificada', 'Forest camp': 'Acampamento na floresta',
    'Field aid station': 'Posto de primeiros socorros', 'Supply depot': 'Depósito de suprimentos',
    'Holdout': 'Reduto', 'Walled compound': 'Complexo murado', 'Cordon bridge checkpoint': 'Bloqueio na ponte'},
'ALifeDebugService.lua': {'Scout Assault': 'Assalto de batedores', 'Area Patrol': 'Patrulha de área',
    'Scavenge Route': 'Rota de coleta', 'Search and Destroy': 'Buscar e destruir', 'Manhunt': 'Caçada humana',
    'Hold Position': 'Manter posição', 'Camp': 'Acampamento', 'Blockade': 'Bloqueio',
    'Outpost Defence': 'Defesa de posto avançado', 'Assault': 'Assalto', 'Full Raid': 'Invasão em grande escala',
    "A-Life: spawn refused (unknown encounter '": "A-Life: geração recusada (encontro desconhecido '",
    'A-Life: spawn refused (': 'A-Life: geração recusada ('},
'ALifeEncounters.lua': {'Patrol': 'Patrulha', 'Hostile Scouts': 'Batedores hostis', 'Full-scale raid': 'Invasão em grande escala',
    'Road crash': 'Acidente na estrada', 'Assassination squad': 'Esquadrão de assassinos', 'Blockade': 'Bloqueio',
    'Highway ambush': 'Emboscada na rodovia', 'Rooftop shooters': 'Atiradores no telhado',
    'Station garrison': 'Guarnição da delegacia', 'Broken-down car': 'Carro quebrado',
    'Town patrol route': 'Rota de patrulha urbana', 'Scavenger crew': 'Grupo de catadores',
    'Building residents (NPCs only)': 'Moradores do prédio (apenas NPCs)'},
'ALifeSquadMap.lua': {'A-Life squads: ': 'Esquadrões A-Life: ', '  |  positions as of ': '  |  posições às ',
    ' game time': ' (hora do jogo)', '  |  refreshes every ': '  |  atualiza a cada ',
    ' game minutes while the map is open  |  hover a dot, right-click for actions':
        ' minutos de jogo com o mapa aberto  |  passe o mouse sobre um ponto, clique direito para ações',
    'A-Life: squad map ON (open the world map, hover a dot)': 'A-Life: mapa de esquadrões LIGADO (abra o mapa do mundo e passe o mouse sobre um ponto)',
    'A-Life: squad map off': 'A-Life: mapa de esquadrões desligado', 'squad deleted': 'esquadrão excluído',
    'squad sent out': 'esquadrão enviado', 'next squad delayed': 'próximo esquadrão adiado',
    'squad cap changed': 'limite de esquadrões alterado', ' removed)': ' removidos)', ' (next in ': ' (próximo em ',
    ' (cap ': ' (limite ', 'A-Life: refused - ': 'A-Life: recusado - ', 'unknown': 'desconhecido'},
'ALifeOutpostRadioMenu.lua': {'[A-LIFE] Outpost radio': '[A-LIFE] Rádio do posto avançado',
    'Disable communications in this outpost': 'Desativar as comunicações deste posto avançado',
    "Use the radio: call the outpost's faction": 'Usar o rádio: chamar a facção do posto avançado',
    'I just cut off all communications for that outpost, go to hell.': 'Acabei de cortar todas as comunicações daquele posto avançado. Vão pro inferno.',
    'Come and get me.': 'Venham me pegar.', "That was their radio. They won't forget who cut it.": 'Era o rádio deles. Não vão esquecer quem cortou.',
    "They're sending people. Hold on.": 'Estão mandando gente. Aguenta firme.',
    'Static... then a voice asking where exactly you are.': 'Estática... e depois uma voz perguntando onde exatamente você está.',
    'Get closer to the radio.': 'Chegue mais perto do rádio.', 'This radio is already dead.': 'Este rádio já está morto.',
    'Dead air. Someone already killed this radio.': 'Silêncio total. Alguém já destruiu este rádio.',
    'The channel is busy. Try again later.': 'O canal está ocupado. Tente de novo mais tarde.',
    'Nobody is listening on this frequency.': 'Ninguém está ouvindo nesta frequência.', 'Slow down.': 'Vá com calma.',
    'Done.': 'Feito.', 'Nothing happens (': 'Nada acontece ('},
'ALifeAnimations.lua': {'None': 'Nenhum', 'Surrender': 'Render-se', 'Wave': 'Acenar', 'Follow me': 'Siga-me', 'Stop': 'Pare',
    'Thumbs up': 'Joinha', 'Salute': 'Continência', 'Yes': 'Sim', 'Shrug': 'Dar de ombros', 'Shout': 'Gritar',
    'Come here': 'Venha aqui', 'Taunt': 'Provocar', 'Thumbs down': 'Polegar para baixo', 'Hesitate': 'Hesitar',
    'Heavy breathing': 'Respiração ofegante', 'Tired stretch': 'Alongamento cansado', 'Refuse': 'Recusar'},
'ALifeStatusWindow.lua': {'Refresh': 'Atualizar', 'Waiting for server status...': 'Aguardando o status do servidor...',
    'Actors: ': 'Atores: ', 'Active / spawning: ': 'Ativos / surgindo: ', 'Dormant / dead: ': 'Inativos / mortos: ',
    'Physical shells: ': 'Corpos físicos: ', 'Running actions: ': 'Ações em andamento: ', 'Pending spawns: ': 'Gerações pendentes: ',
    'Watchdog recoveries: ': 'Recuperações do watchdog: ', 'disabled': 'desativado', 'enabled': 'ativado', 'Health: ': 'Saúde: ',
    ' error(s)': ' erro(s)', 'Runtime faults / overruns: ': 'Falhas / estouros de execução: ', 'Protected areas: ': 'Áreas protegidas: ',
    'Tick ms (last / max): ': 'Tick ms (último / máx.): ', 'Tick count / budget: ': 'Contagem de ticks / orçamento: ',
    'Reputation (last known)': 'Reputação (última conhecida)', 'No faction overrides': 'Sem substituições de facção',
    'Project A-Life Status': 'Status do Project A-Life'},
'ALifeTalkMenu.lua': {'A-LIFE  /  CONVERSATION': 'A-LIFE  /  CONVERSA', 'More topics': 'Mais assuntos',
    '[Leave]  See you around.': '[Sair]  Até mais.', 'Survivor': 'Sobrevivente', 'Waiting for a reply': 'Aguardando resposta',
    'More  /  ': 'Mais  /  ', ' of ': ' de ', "Yeah... I'm doing alright.": 'É... estou me virando.', 'No. Not really.': 'Não. Na verdade, não.',
    'Ask to travel with their group; this does not recruit or command them.': 'Pedir para viajar com o grupo deles; isso não os recruta nem os coloca sob seu comando.',
    'You': 'Você', 'The conversation system is not loaded. Restart after updating the mod.': 'O sistema de conversa não está carregado. Reinicie depois de atualizar o mod.',
    'No reply yet. You can try again.': 'Sem resposta ainda. Você pode tentar de novo.',
    'Get within six tiles, on the same floor.': 'Fique a até seis quadrados, no mesmo andar.',
    'Get on the same side of the wall first.': 'Primeiro fique do mesmo lado da parede.',
    "They're hostile. This isn't a good time to chat.": 'Está hostil. Não é uma boa hora para conversar.',
    "They're fighting. Try again when it's safe.": 'Estão lutando. Tente de novo quando for seguro.',
    "They don't trust you enough to travel together.": 'Não confiam em você o bastante para viajarem juntos.',
    "They haven't asked you a yes-or-no question.": 'Não te fizeram nenhuma pergunta de sim ou não.',
    'Give them a second.': 'Dê um segundo a eles.', 'They have nothing to add right now.': 'Não têm mais nada a dizer agora.',
    'NPC conversations are disabled on this server.': 'Conversas com NPCs estão desativadas neste servidor.',
    'That person is no longer available.': 'Essa pessoa não está mais disponível.',
    "They aren't answering right now.": 'Não estão respondendo agora.',
    '[A-LIFE] Talk to someone nearby': '[A-LIFE] Falar com alguém por perto', 'Survivor ': 'Sobrevivente '},
'ALifeSquadMapOverlay.lua': {'Send a squad out now': 'Enviar um esquadrão agora', 'Delay next squad by 1 hour': 'Adiar próximo esquadrão em 1 hora',
    'Delay next squad by 24 hours': 'Adiar próximo esquadrão em 24 horas', 'Delay next squad by 7 days': 'Adiar próximo esquadrão em 7 dias',
    'Delay next squad by 30 days': 'Adiar próximo esquadrão em 30 dias', 'Max squads +1': 'Máx. de esquadrões +1',
    'Max squads -1': 'Máx. de esquadrões -1', 'Delete this squad (': 'Excluir este esquadrão (', ' person)': ' pessoa)',
    ' people)': ' pessoas)', 'under a minute': 'menos de um minuto', 'squad': 'esquadrão', 'outpost': 'posto avançado',
    'offline squad': 'esquadrão offline', ' person': ' pessoa', ' people': ' pessoas', 'From: ': 'Origem: ', 'Task: ': 'Tarefa: ',
    'Now: ': 'Agora: ', 'Going to: ': 'Indo para: ', 'Arrives in ': 'Chega em ', ' (game time)': ' (hora do jogo)',
    'Next squad in ': 'Próximo esquadrão em ', 'Squads out: ': 'Esquadrões na rua: ', ' of ': ' de ',
    'Saved with the world': 'Salvo com o mundo', 'This session only': 'Só nesta sessão', 'Right-click for actions': 'Clique direito para ações'},
'ALifeContextMenu.lua': {'Edit NPC...': 'Editar NPC...', 'Persistent': 'Persistente', 'Stationary': 'Parado', 'Leash radius...': 'Raio de alcance...',
    'Off': 'Desligado', ' tiles': ' quadrados', 'Loading factions - reopen this menu': 'Carregando facções - reabra este menu',
    'Automatic faction': 'Facção automática', 'Loading faction choices - reopen menu': 'Carregando opções de facção - reabra o menu',
    'Runtime status': 'Status de execução', 'Open faction & NPC Creator': 'Abrir Criador de facções e NPCs',
    'Open spawn panel': 'Abrir painel de geração', 'Spawn faction squad here...': 'Gerar esquadrão de facção aqui...',
    'Spawn encounter here...': 'Gerar encontro aqui...', 'Delete nearest outpost': 'Excluir posto avançado mais próximo',
    'Build staffed outpost here...': 'Construir posto avançado com guarnição aqui...',
    'Configure full-scale raid...': 'Configurar invasão em grande escala...', 'Play a meta event here...': 'Tocar um evento de ambiente aqui...',
    'Distant gunfire': 'Tiros distantes', 'Helicopter': 'Helicóptero', 'Car crash': 'Batida de carro',
    'Ambience (siren, scream, radio)': 'Ambiente (sirene, grito, rádio)', 'Session siren': 'Sirene da sessão',
    'Diagnostics...': 'Diagnósticos...', 'Toggle encounter arrows': 'Alternar setas de encontro',
    'Toggle A-Life squads on world map': 'Alternar esquadrões A-Life no mapa do mundo',
    'Dump module QA to console.txt': 'Despejar QA dos módulos em console.txt',
    'Silence world audio (stuck helicopter)': 'Silenciar áudio do mundo (helicóptero travado)', 'Remove NPCs...': 'Remover NPCs...',
    'Within ': 'Num raio de ', ' tiles of here': ' quadrados daqui', 'A-Life: removing actors within ': 'A-Life: removendo atores num raio de ',
    'Every A-Life NPC on the map': 'Todos os NPCs A-Life do mapa', 'A-Life: removing every actor': 'A-Life: removendo todos os atores',
    'Every squad on the map': 'Todos os esquadrões do mapa', 'A-Life: removing every squad': 'A-Life: removendo todos os esquadrões',
    'Reset creator overrides': 'Redefinir alterações do Criador',
    'A-Life: custom profiles and factions cleared': 'A-Life: perfis e facções personalizados apagados'},
'ALifeTalkIntents.lua': {'Good to see another person.': 'Bom ver outra pessoa.', 'Hey. Good to see somebody alive.': 'Ei. Bom ver alguém vivo.',
    "Didn't expect company out here.": 'Não esperava companhia por aqui.', 'Mind if we talk a minute?': 'Se importa se a gente conversar um minuto?',
    'Heard anything around here?': 'Ouviu alguma coisa por aqui?', 'Where are you headed?': 'Para onde você está indo?',
    'Got any advice?': 'Tem algum conselho?', 'Got any food to spare?': 'Tem comida sobrando?',
    'What did you do before all this?': 'O que você fazia antes de tudo isso?', 'What happened to the army?': 'O que aconteceu com o exército?',
    'Any word from the National Guard?': 'Alguma notícia da Guarda Nacional?', "Think the army's still out there?": 'Acha que o exército ainda está por aí?',
    'You heard anything about the soldiers?': 'Ouviu alguma coisa sobre os soldados?', 'You heard anything about Fort Knox?': 'Ouviu alguma coisa sobre Fort Knox?',
    'How did it get this bad?': 'Como as coisas ficaram tão ruins?', 'Anything useful on the radio?': 'Alguma coisa útil no rádio?',
    'Anything I should watch out for here?': 'Tem algo com que eu deva tomar cuidado por aqui?',
    'You got a story? I could use a distraction.': 'Tem alguma história? Uma distração cairia bem.',
    'You got family out there?': 'Você tem família por aí?', 'Who are you running with?': 'Com quem você anda?',
    'What do you miss most?': 'Do que você mais sente falta?', 'Know where I can find drinking water?': 'Sabe onde posso achar água potável?',
    'Can you spare any medical supplies?': 'Pode me arranjar algum suprimento médico?',
    'Anywhere worth checking for supplies?': 'Algum lugar que valha a pena procurar suprimentos?',
    'Yeah, alright.': 'Tá, pode ser.', 'No, not right now.': 'Não, agora não.',
    'Heard anything I ought to know?': 'Ouviu algo que eu deveria saber?', "What's the word around here?": 'O que andam dizendo por aqui?',
    'Any news from outside town?': 'Alguma notícia de fora da cidade?', 'Where are you headed next?': 'Para onde você vai agora?',
    'You staying around here?': 'Vai ficar por aqui?', "What's your next stop?": 'Qual é a sua próxima parada?',
    'What have you figured out so far?': 'O que você já descobriu até agora?', 'Any advice for staying alive?': 'Algum conselho pra continuar vivo?',
    "Anything you wish you'd known sooner?": 'Algo que você queria ter sabido antes?', 'You have any food you can spare?': 'Tem alguma comida pra dividir?',
    "Got anything to eat? I'm running low.": 'Tem algo pra comer? Estou quase sem nada.', 'Could you spare a bite?': 'Pode me dar um pedaço?',
    'What was your work, before this?': 'Qual era o seu trabalho, antes disso?', 'What did a normal day look like for you?': 'Como era um dia normal pra você?',
    'You from around here? What did you do?': 'Você é daqui? O que você fazia?'},
'ALifeEncounterConsole.lua': {'HOLDS A LINE': 'SEGURA UMA LINHA', 'HOLDS A BUILDING': 'OCUPA UM PRÉDIO', 'HOLDS A FLOOR': 'OCUPA UM ANDAR',
    'HOLDS A PLACE': 'OCUPA UM LUGAR', 'WALKS A CIRCUIT': 'PERCORRE UM CIRCUITO', 'WORKS ON A CAR': 'CONSERTA UM CARRO',
    'LIVES AT A CAMP': 'VIVE NUM ACAMPAMENTO', '(empty)': '(vazio)', 'A-LIFE  ::  ENCOUNTER CONSOLE': 'A-LIFE  ::  CONSOLE DE ENCONTROS',
    'Choose a squad and encounter, then deploy both with one action.': 'Escolha um esquadrão e um encontro e posicione os dois com uma só ação.',
    'Faction: ': 'Facção: ', 'SPAWN ENCOUNTER + SQUAD': 'GERAR ENCONTRO + ESQUADRÃO', 'ADVANCED OPTIONS  >': 'OPÇÕES AVANÇADAS  >',
    'SIMULATE HERE': 'SIMULAR AQUI', 'SIMULATE BY RULE': 'SIMULAR PELA REGRA', 'SPAWN FACTION SQUAD': 'GERAR ESQUADRÃO DE FACÇÃO',
    'PERSISTENT: DEFAULT': 'PERSISTENTE: PADRÃO', 'ENCOUNTER ARROWS': 'SETAS DE ENCONTRO', 'SQUADS ON WORLD MAP': 'ESQUADRÕES NO MAPA DO MUNDO',
    'BLACK BOX DUMP': 'DESPEJAR CAIXA-PRETA', 'MODULE QA DUMP': 'DESPEJAR QA DOS MÓDULOS', 'REFRESH': 'ATUALIZAR',
    'ADVANCED OPTIONS  v': 'OPÇÕES AVANÇADAS  v', ' NPCs': ' NPCs', 'FIGHTS AND MOVES': 'LUTA E SE MOVE', ' profiles': ' perfis',
    'REFRESH REFUSED: ': 'ATUALIZAÇÃO RECUSADA: ', 'unknown': 'desconhecido', 'Module QA written to ': 'QA dos módulos gravado em ',
    'Black box written to ': 'Caixa-preta gravada em ', ' DUMP REFUSED: ': ' - DESPEJO RECUSADO: ',
    ' + ||~= nil and (': ' + cena ', 'Queued ': 'Na fila: ', 'REFUSED: ': 'RECUSADO: ', 'Pick an encounter first.': 'Escolha um encontro primeiro.',
    'No position for this player.': 'Sem posição para este jogador.', 'Building ': 'Montando ', 'encounter': 'encontro',
    ' + ||or "encounter" ) ..': ' + esquadrão ', 'automatic': 'automático', ' squad...': '...',
    'Simulating here...': 'Simulando aqui...', "Placing by the encounter's own rule...": 'Posicionando pela regra do próprio encontro...',
    'Pick a faction first.': 'Escolha uma facção primeiro.', 'Spawning ': 'Gerando esquadrão de ',
    'PERSISTENT: YES': 'PERSISTENTE: SIM', 'PERSISTENT: NO': 'PERSISTENTE: NÃO',
    'Requesting black box dump...': 'Solicitando despejo da caixa-preta...', 'Requesting module QA dump...': 'Solicitando despejo do QA dos módulos...',
    '1  SQUAD': '1  ESQUADRÃO', '2  ENCOUNTER': '2  ENCONTRO', '3  DEPLOY': '3  POSICIONAR', 'SIZE: ': 'TAMANHO: ',
    'SCENE + SQUAD, ONE DEPLOY': 'CENA + ESQUADRÃO, UM SÓ POSICIONAMENTO', 'Advanced: place / size / persist': 'Avançado: local / tamanho / persistência',
    'tile ': 'quadrado ', 'player position': 'posição do jogador', 'Target: ': 'Alvo: ', 'rolls ': 'sorteios ', '  placed ': '  posicionados ',
    '  refused ': '  recusados ', '(nothing yet)': '(nada ainda)', '(no report yet)': '(sem relatório ainda)', 'ON THE MAP': 'NO MAPA',
    '   ': '   há ', 's ago': 's', 'nothing placed yet': 'nada posicionado ainda'},
}
