# Sandbox.json PT-BR, entries 95-199. Keep "%%" as in the EN file.
PT = {
95: 'Quantos postos avançados uma cidade pode ter.',
96: 'Sorteio de posto avançado a cada (minutos)',
97: 'Com que frequência o mundo sorteia um novo posto avançado, em minutos de jogo (dormir e acelerar o tempo também contam). Num mundo com o relógio parado, vale o mesmo número de minutos reais.',
98: 'Chance do sorteio de posto avançado (%%)',
99: 'A chance de cada sorteio criar um novo posto avançado.',
100: 'Postos avançados são construídos a até (quadrados)',
101: 'Um posto avançado proposto só é construído enquanto um jogador estiver a esta distância (para que o terreno esteja carregado), e nunca a menos de 40 quadrados de alguém.',
102: 'A guarnição surge a até (quadrados)',
103: 'Um posto avançado construído recebe a guarnição quando um jogador chega a esta distância.',
104: 'Esquadrões chamam reforços',
105: 'Um esquadrão em contato pode chamar um esquadrão de reação rápida; chamadas limitadas, uma recarga e uma chance real de ninguém responder.',
106: 'Multiplicador da frequência de encontros',
107: 'Ajusta a frequência geral de encontros. Um é o padrão equilibrado.',
108: 'Multiplicador do tamanho dos grupos',
109: 'Ajusta o tamanho dos grupos hostis naturais.',
110: 'Raio da simulação detalhada',
111: 'Distância em quadrados na qual os atores persistentes ganham corpo físico.',
112: 'Máximo de atores hostis vivos',
113: 'Limite rígido de atores hostis persistentes naturais.',
114: 'Chance de encontro por verificação (porcentagem)',
115: 'Chance por sorteio para os dois geradores naturais: o diretor de facções sorteia uma vez a cada intervalo de verificação de encontros, o diretor de encontros uma vez a cada intervalo de sorteio de encontros. Padrão 25.',
116: 'Intervalo de verificação de encontros (horas de jogo)',
117: 'Horas de jogo entre verificações de encontros hostis naturais.',
118: 'Margem de exclusão de abrigos',
119: 'Quadrados extras sem geração em volta dos abrigos (safehouses) do multijogador.',
120: 'Conflito entre facções hostis',
121: 'Permite que facções hostis do A-Life lutem entre si.',
122: 'Permitir recuo',
123: 'NPCs hostis feridos podem recuar.',
124: 'Permitir coleta',
125: 'Saqueadores hostis podem pegar suprimentos próximos.',
126: 'Investigar perturbações',
127: 'Hostis vão na direção de tiros, gritos e outros rastros que percebem.',
128: 'Reagrupar com o líder',
129: 'Membros que ficam para trás voltam a se juntar ao grupo em vez de se dispersarem.',
130: 'Mover-se em grupo',
131: 'Os grupos viajam juntos em formação, e não como andarilhos separados.',
132: 'Permitir que armas caiam',
133: 'Armas elegíveis dos NPCs podem ficar no inventário do cadáver.',
134: 'Chance de a arma cair',
135: 'Com que frequência a arma de fogo ou corpo a corpo de um NPC morto fica no corpo. Por perfil de NPC mantém a chance própria de cada perfil definida no Criador. Qualquer outra opção é a chance para todos os NPCs. Uma geração pelo painel de admin continua usando a própria linha. Exige Permitir que armas caiam ligado.',
136: 'Por perfil de NPC',
137: 'Desligado (0%%)',
138: 'Muito baixa (0-10%%)',
139: 'Baixa (10-20%%)',
140: 'Moderada (20-30%%)',
141: 'Alta (30-50%%)',
142: 'Muito alta (50-70%%)',
143: 'Quase sempre (70-99%%)',
144: 'Sempre (100%%)',
145: 'Estado da arma que cai',
146: 'Em que estado fica uma arma que cai. Por perfil de NPC mantém a nota própria de cada perfil e a curva do começo de jogo, em que as primeiras semanas dão principalmente armas quebradas ou quase quebradas. Qualquer outra opção é o estado de toda arma que cai, de todos os NPCs. Quebrada significa que precisa ser consertada antes de funcionar. O NPC continua lutando com ela com força total.',
147: 'Por perfil de NPC',
148: 'Quebrada (0/10)',
149: 'Sucata, um ou dois tiros (1/10)',
150: 'Muito ruim, poucos tiros (2/10)',
151: 'Ruim (3/10)',
152: 'Gasta (4/10)',
153: 'Usada, meio gasta (5/10)',
154: 'Utilizável (6/10)',
155: 'Boa (7/10)',
156: 'Muito boa (8/10)',
157: 'Quase nova (9/10)',
158: 'Nova em folha (10/10)',
159: 'Ativar travamento das armas dos NPCs',
160: 'Armas de fogo dos NPCs que não são revólveres podem falhar o disparo, dar clique e depois ser destravadas à vista.',
161: 'Chance de travamento da arma do NPC (porcentagem)',
162: 'Chance base, por puxada de gatilho, de uma arma de fogo de NPC que não seja revólver travar. Zero desativa os travamentos mesmo com o recurso ligado.',
163: 'Força de arrombamento dos NPCs (porcentagem)',
164: 'Com que força os NPCs atacam uma porta, janela ou barricada quando invadem. 100 é o padrão testado: uma janela leva três golpes, uma tábua quatro, uma porta comum cerca de meio minuto, e só um homem golpeia enquanto os outros o cobrem. Diminua e eles demoram mais; aumente e eles entram mais rápido.',
165: 'Acerto múltiplo dos NPCs (experimental)',
166: 'Um golpe com arma de duas mãos de um NPC atinge também um segundo zumbi que esteja no arco, com três quartos da força. Só zumbis, nunca pessoas. Desligado por padrão.',
167: 'Penetração de balas (experimental)',
168: 'Uma bala que um NPC acerta num zumbi continua até o zumbi logo atrás (até três quadrados). Só zumbis, nunca pessoas; melhor contra uma horda. Desligado por padrão.',
169: 'Povoar lugares no início (experimental)',
170: 'Uma vez por mundo, os cômodos das cidades são lidos e parte dos lugares que um sobrevivente ocuparia -- delegacias, quartéis de bombeiros, clínicas e o dentista, lojas de armas, armazéns, postos de gasolina, motéis, lanchonetes, igrejas, escolas, lojas e casas -- é marcada para ser ocupada: Raro 10%%, Incomum 20%%, Comum 35%% deles, com pelo menos dois por cidade. Um lugar marcado recebe seus moradores na primeira vez que um jogador chega perto, de uma facção que combine com o cômodo: polícia na delegacia, bombeiros no quartel, equipe do hospital na ala, uma família numa casa. Eles são persistentes e salvos com o mundo.',
171: 'Desligado',
172: 'Raro',
173: 'Incomum',
174: 'Comum',
175: 'Máximo de lugares povoados',
176: 'O máximo de lugares no mundo inteiro que Povoar lugares no início pode ocupar. Os lugares mais importantes (delegacias, quartéis de bombeiros, clínicas) têm prioridade.',
177: 'Procurar alvos perdidos',
178: 'Os NPCs vão até onde um alvo foi visto por último e varrem a área antes de desistir.',
179: 'Reagir aos gritos do jogador',
180: 'Gritar atrai na sua direção todos os NPCs que conseguem ouvir.',
181: 'Avisos de localização no grupo',
182: 'Um NPC que avista algo avisa o grupo onde está, uma vez. Não é um rastreamento em tempo real.',
183: 'Investigar rastros do jogador',
184: 'Sem nada para combater, os NPCs revistam áreas onde notam sinais de sobreviventes.',
185: 'Notar veículos',
186: 'Um veículo ligado ou com ligação direta marca a área em volta como digna de busca.',
187: 'Notar barricadas',
188: 'Janelas e portas com tábuas marcam um prédio como sendo de alguém.',
189: 'Notar paredes construídas',
190: 'Paredes, portões e cercas construídos por jogadores marcam um local como ocupado.',
191: 'Notar geradores ligados',
192: 'Um gerador ativo é um forte indício de que alguém mora por perto.',
193: 'Disposição para investigar rastros',
194: 'Ajusta a facilidade com que os NPCs reagem a rastros. Mais alto investiga indícios mais fracos; mais baixo exige uma pista mais forte.',
195: 'Áudio de voz dos NPCs',
196: 'Toca clipes de voz gravados para o que os NPCs dizem. Desligado por padrão: os NPCs falam só em texto. Sons de dor e de morte não são afetados.',
197: 'Mostrar ferramentas de admin no menu do clique direito',
198: 'O painel de geração, a lista de encontros, o construtor de postos avançados e a configuração de invasões. Desligue para um menu de clique direito mais limpo; Status de execução e o Criador continuam lá de qualquer forma. Admins num servidor não são afetados.',
199: 'NPCs sofrem dano de veículos',
}
