# Sandbox.json PT-BR, entries 0-94 (index = order in the EN file).
PT = {
0: 'Project A-Life - GERAL',
1: 'Project A-Life - POPULAÇÃO',
2: 'Project A-Life - ENCONTROS',
3: 'Project A-Life - COMPORTAMENTO',
4: 'Project A-Life - COMBATE',
5: 'Project A-Life - INVASÕES E APOIO',
6: 'Predefinição do mundo (ajusta todas as opções abaixo)',
7: 'Um único controle para todos os números abaixo. Define quantos sobreviventes o mundo tem, quantas cidades começam ocupadas, com que frequência você os encontra, se viajam sozinhos ou em grupo, quantos postos avançados existem, quando as invasões começam e o intervalo entre elas, e o tamanho de uma onda de invasão, de um grupo de batedores ou de uma chamada de reforço. Equilibrado é o padrão testado e não grava nada, então um save existente mantém todos os números que já tem. Qualquer opção que você mesmo definir continua valendo: a predefinição só mexe nas opções que estão no próprio padrão, então ajuste um controle e a predefinição não vai tocar nele -- a única coisa que ela não consegue perceber é você escolher de propósito o valor que já era o padrão. Insano passa de propósito dos limites do próprio mod: até 220 hostis ativos (teto testado: 120), 24 postos avançados (12), 4 por cidade (2), 12 acampamentos ao ar livre (6), 40 esquadrões offline (24), 4 esquadrões de tarefa por posto avançado (2) e grupos de batedores de 8 (3). Não foi testado nesses números -- espere um servidor mais pesado, espere bugs e faça backup do seu save antes.',
8: 'Deserto -- quase ninguém sobrou',
9: 'Escasso -- alguns sobreviventes solitários',
10: 'Equilibrado -- o padrão testado (sem mudanças)',
11: 'Lotado -- grupos, postos avançados e invasões frequentes',
12: 'Insano -- além dos limites testados, sem suporte',
13: 'Surto realista',
14: 'Os primeiros dias do surto, do jeito que seriam. A polícia defende suas delegacias e as famílias, suas casas (as cidades começam ocupadas, a menos que você mesmo defina essa opção), a Guarda Nacional mantém um posto de controle na ponte ao norte de West Point e os três primeiros dias trazem mais de tudo. Depois do dia 3, a polícia e o exército somem das estradas de vez; o posto de controle da ponte é abandonado depois de 72 horas e tudo o que ele colocou é removido. Ligado por padrão.',
15: 'Limite de esquadrões salvos',
16: 'Máximo de esquadrões mantidos entre sessões, padrão 3. Isso não limita novos esquadrões offline durante a sessão atual. Os outros grupos duram esta sessão do servidor. As estruturas dos postos avançados são salvas à parte. Diminuir o limite aposenta os esquadrões salvos em excesso no próximo carregamento, não na frente dos jogadores.',
17: 'Esquadrões de tarefa temporários por posto avançado',
18: 'Equipes simultâneas de patrulha, coleta ou caça saindo de cada posto avançado. Padrão 1; zero desativa as saídas. Os grupos duram só a sessão; o local continua salvo.',
19: 'Peso de sobreviventes solitários',
20: 'Frequência relativa de grupos naturais de 1 a 3 pessoas. Alterações de facção têm prioridade.',
21: 'Peso de grupos',
22: 'Frequência relativa de grupos naturais de 4 ou mais pessoas. O padrão é um grupo para cada três solitários.',
23: 'Intervalo de criação offline (horas de jogo)',
24: 'Tempo mínimo entre novos grupos offline, padrão 1,5; o limite de esquadrões offline continua valendo.',
25: 'Ativar invasões lideradas por batedores',
26: 'Invasões automáticas exigem um grupo de batedores inimigo gerado com sucesso, tempo de preparação e o dia mínimo. O painel de admin pode forçar uma invasão.',
27: 'Primeiro dia possível de invasão',
28: 'Invasões automáticas não podem começar antes deste dia de idade do mundo.',
29: 'Recarga entre invasões (dias de jogo)',
30: 'Tempo mínimo entre invasões automáticas em grande escala.',
31: 'Chance de invasão/batedores por verificação (porcentagem)',
32: 'Chance de começar a preparação com batedores a cada verificação (a cada 10 minutos de jogo por padrão). O padrão de 0,02 com recarga de 14 dias dá mais ou menos uma invasão em grande escala a cada seis ou sete semanas. 0 desliga as invasões automáticas.',
33: 'Intervalo de verificação (minutos de jogo)',
34: 'Com que frequência o diretor de invasões verifica se uma invasão automática pode acontecer.',
35: 'Ondas da invasão',
36: 'Número de ondas de ataque por invasão.',
37: 'NPCs por onda de invasão',
38: 'Atacantes pedidos em cada onda. A geração ainda respeita os limites em jogo.',
39: 'Intervalo entre ondas (minutos de jogo)',
40: 'Espaça as ondas de reforço depois do aviso inicial.',
41: 'Helicópteros',
42: 'Todos os helicópteros do A-Life: descidas de invasão e de reforço, holofotes noturnos e sobrevoos. Desligado significa que nenhum deles voa.',
43: 'Preparação dos batedores (horas de jogo)',
44: 'Tempo de espera depois que os batedores chegam com sucesso antes que uma invasão possa começar.',
45: 'Validade das informações dos batedores (horas de jogo)',
46: 'Um relatório de batedores vencido não autoriza uma invasão; novos batedores precisam ser enviados.',
47: 'Tamanho do grupo de batedores inimigo',
48: 'Número de batedores inimigos enviados antes de uma invasão automática em grande escala.',
49: 'Sucesso da chamada de reforço (porcentagem)',
50: 'Chance de uma chamada de apoio permitida dar certo.',
51: 'Recarga do reforço (horas de jogo)',
52: 'Tempo mínimo de jogo entre chamadas bem-sucedidas do mesmo grupo.',
53: 'Tamanho padrão do esquadrão de reforço',
54: 'Usado quando quem chama/a facção não tem um tamanho de apoio definido.',
55: 'Máximo de chamadas de reforço por grupo',
56: 'Limita pedidos repetidos de reforço de um mesmo grupo.',
57: 'Chance de chamar holofote (porcentagem)',
58: 'Chance de uma chamada autorizada de holofote de helicóptero. Quem só chama apoio terrestre não pode usar.',
59: 'Duração do holofote (segundos reais)',
60: 'Segue o jogador alvo enquanto ele está ao ar livre; apaga quando ele entra.',
61: 'Duração do apoio de helicóptero (segundos reais)',
62: 'Duração da apresentação do helicóptero de apoio virtual.',
63: 'Raio de busca de prédios para coleta',
64: 'Distância máxima para escolher um prédio próximo; valores maiores aumentam o trabalho de busca.',
65: 'Itens coletados antes de voltar',
66: 'Máximo de itens recolhidos antes de voltar para o depósito do acampamento/base.',
67: 'Voltar depois de revistar prédios',
68: 'Levar os suprimentos para casa depois de revistar esta quantidade de prédios.',
69: 'Ativar A-Life hostil',
70: 'Desligado: nenhuma facção hostil é gerada, e as invasões e os postos avançados param. NPCs amigáveis, neutros e cautelosos continuam aparecendo.',
71: 'NPCs à noite',
72: 'Lanternas: os NPCs carregam uma luz e enxergam 12 quadrados no escuro (20 com a luz em você). Visão noturna: os NPCs simplesmente enxergam à noite; dê os óculos a eles você mesmo.',
73: 'Lanternas',
74: 'Visão noturna',
75: 'Chance de atividade noturna',
76: 'Probabilidade de um esquadrão continuar se movendo e trabalhando depois que escurece. Os outros procuram uma casa para a noite ou montam acampamento: fecham as cortinas, penduram lençóis nas janelas, ficam quietos até de manhã e deixam os mortos lá fora em paz. Sem riscos: todo mundo se esconde. Arriscados: quase ninguém se esconde.',
77: 'Sem riscos',
78: 'Chance baixa',
79: 'Chance moderada',
80: 'Chance alta',
81: 'Arriscados',
82: 'Esquadrões offline no mapa',
83: 'Máximo de esquadrões offline circulando durante uma sessão, padrão 6. 0 desliga o mundo offline; os encontros da sessão por perto e os postos avançados salvos continuam. O Limite de esquadrões salvos, à parte, controla quantos voltam na próxima sessão, sem impedir que novos esquadrões sejam criados agora.',
84: 'Atualização offline a cada (segundos)',
85: 'Com que frequência os esquadrões offline se movem e tomam decisões.',
86: 'Velocidade de viagem offline (quadrados por hora)',
87: 'Quanto um esquadrão offline anda em uma hora de jogo. Padrão 150, um ritmo de caminhada com a duração de dia padrão; as cidades ficam a 1700-3400 quadrados umas das outras.',
88: 'Esquadrões guardam rancor',
89: 'Um esquadrão que perdeu gente para você e escapou volta atrás de você dois ou três dias depois, com reforços.',
90: 'Postos avançados surgem com o tempo',
91: 'Delegacias fortificadas, casas ocupadas e acampamentos na floresta aparecem com o tempo, guarnecidos por gente que nunca sai.',
92: 'Postos avançados ao mesmo tempo (máx.)',
93: 'Quantos postos avançados podem existir ao mesmo tempo. 0 desliga.',
94: 'Postos avançados por cidade',
}
