# Sandbox.json PT-BR, entries 200-289.
PT = {
200: 'Um veículo em movimento machuca o NPC que atinge, conforme a velocidade. Desligue para que a verificação de veículos nem rode. De qualquer forma, os NPCs continuam sem conseguir te alcançar pela janela intacta de um carro.',
201: 'Mira dos NPCs contra jogadores',
202: 'Com que frequência os tiros dos NPCs acertam jogadores. Médio é a habilidade de mira de cada NPC, sem alterações. Muito fácil é 40%% dela, Fácil 65%%, Difícil 125%%, Muito difícil 150%%, Extremo 180%%. A precisão contra zumbis é definida na página Combate.',
203: 'Muito fácil',
204: 'Fácil',
205: 'Médio',
206: 'Difícil',
207: 'Muito difícil',
208: 'Extremo',
209: 'Precisão dos NPCs contra zumbis (%%)',
210: 'Ajusta com que frequência os tiros dos NPCs acertam um ZUMBI. 100 é sem alteração; aumente se os grupos parecerem indefesos contra uma horda. Não afeta a mira deles contra você.',
211: 'Mostrar rastro das balas',
212: 'Desenha um rastro visível em cada tiro que um NPC dispara. O clarão do cano, o som dos tiros e as cápsulas não mudam de qualquer forma.',
213: 'Atiradores usam cobertura',
214: 'NPCs armados saem da linha de tiro para recarregar, rompem o contato quando feridos e lutam atrás de paredes e esquinas.',
215: 'Atiradores recuam e voltam ao combate',
216: 'Um atirador que está perdendo rompe o contato, recua cerca de um quarteirão, se esconde fora de vista -- dentro de um prédio, se houver -- e depois volta por outro lado. Só à distância; corpo a corpo sempre avança.',
217: 'Módulo: tratar ferimentos',
218: 'Depois de uma luta, um NPC ferido para, faz curativo e deixa de mancar e sangrar.',
219: 'Ferimentos e sangramento dos NPCs',
220: 'Os golpes deixam marcas nos NPCs: um ferimento na perna os impede de correr, e abaixo de dez por cento de vida eles sangram até morrer em segundos, a menos que façam curativo.',
221: 'Movimento: arrancadas',
222: 'Permite arrancadas para fechar distância no corpo a corpo, ir para a cobertura e recuar. Desligado mantém esses movimentos correndo ou andando.',
223: 'Comportamento: supressão do metralhador',
224: 'Um atirador que perde o alvo de vista esvazia o carregador na última posição conhecida, no automático, varrendo para os lados. Pistolas também descarregam.',
225: 'Encontros aleatórios',
226: 'O diretor de encontros: patrulhas, invasões, grupos de coleta, esquadrões de assassinos e guarnições sorteados do catálogo perto dos jogadores, posicionados pelas próprias zonas de cidade do mapa.',
227: 'Intervalo de sorteio de encontros (minutos de jogo)',
228: 'Minutos de jogo entre os sorteios do diretor de encontros (dormir e acelerar o tempo também contam). Padrão 60, de 10 a 720. A chance de geração por sorteio vem da opção de chance de encontro.',
229: 'Vida útil de NPC não visitado (horas do mundo)',
230: 'Um NPC estacionado de quem ninguém se aproximou por esta quantidade de horas de jogo é removido. NPCs persistentes (âncoras de admin, guarnições de encontro) nunca expiram. 0 desativa a limpeza.',
231: 'Condutas dos NPCs (líder, atirador de elite, médico...)',
232: 'A camada de condutas: líderes de esquadrão que posicionam e reagrupam o grupo, atiradores de elite que mantêm distância, médicos que tratam os feridos, emboscadores que esperam no escuro, assassinos furtivos. Desligado desativa todas as condutas de uma vez.',
233: 'Atiradores miram enquanto se movem',
234: 'NPCs armados mantêm a arma no alvo, ou onde ele foi visto por último, enquanto andam, recuam ou se deslocam para o lado.',
235: 'Modo de mundo do A-Life',
236: 'Completo: esquadrões circulam pelo mapa inteiro enquanto ninguém está perto (simulação offline) e aparecem quando você chega perto; postos avançados surgem e caem por conta própria. Só local: sem esquadrões offline -- os grupos de NPCs só existem perto dos jogadores (mais leve); os postos avançados continuam surgindo.',
237: 'A-Life completo (esquadrões offline circulam pelo mapa)',
238: 'Só local (grupos perto dos jogadores; postos avançados continuam)',
239: 'Taxa de encontros',
240: 'Com que frequência o diretor de encontros sorteia um novo grupo perto dos jogadores. Baixa corta a chance pela metade, Abundante a triplica (o intervalo de sorteio não muda).',
241: 'Baixa', 242: 'Normal', 243: 'Alta', 244: 'Muito alta', 245: 'Abundante',
246: 'Taxa de grupos errantes',
247: 'Quantos grupos o mundo mantém: o multiplicador de geração e o limite de esquadrões offline juntos. Baixa corta os dois pela metade, Abundante os triplica (dentro dos próprios tetos).',
248: 'Baixa', 249: 'Normal', 250: 'Alta', 251: 'Muito alta', 252: 'Abundante',
253: 'Taxa de sobreviventes',
254: 'Com que frequência as facções amigáveis ou neutras ao jogador são escolhidas quando um grupo é criado. Baixa corta o peso delas pela metade em relação às hostis, Abundante o triplica.',
255: 'Baixa', 256: 'Normal', 257: 'Alta', 258: 'Muito alta', 259: 'Abundante',
260: 'Taxa de eventos de ambiente',
261: 'Tiros distantes, helicópteros, batidas de carro e o ambiente do mundo: Baixa corta pela metade os limites diários e semanais e dobra o intervalo entre eventos, Abundante triplica os limites e encurta o intervalo.',
262: 'Baixa', 263: 'Normal', 264: 'Alta', 265: 'Muito alta', 266: 'Abundante',
267: 'Acampamentos e bases de campo fora das cidades (máx.)',
268: 'Quantos locais ao ar livre -- acampamentos na floresta, bases de campo, postos de socorro, depósitos -- podem existir ao mesmo tempo, além do limite por cidade para prédios fortificados. 0 desativa os locais ao ar livre.',
269: 'Patrulhas descansam',
270: 'Patrulhas e grupos de batedores param fora da estrada a cada poucas horas e depois de uma luta: em roda, um senta, um fuma, os outros bebem e conversam, e depois retomam a rota.',
271: 'Descanso da patrulha: mínimo (minutos de jogo)',
272: 'O descanso mais curto, em minutos de jogo.',
273: 'Descanso da patrulha: máximo (minutos de jogo)',
274: 'O descanso mais longo, em minutos de jogo.',
275: 'Descanso da patrulha: a cada (horas de jogo)',
276: 'Horas de jogo entre descansos programados, por esquadrão, com alguma variação. O descanso depois de uma luta acontece por conta própria.',
277: 'NPCs respondem a jogadores que falam',
278: 'Digite no chat perto de NPCs e eles respondem: perguntas, pedidos, ameaças, sim ou não. Eles também reagem com palavras quando você os atinge ou os ajuda numa luta.',
279: 'Caixa de chat no modo solo',
280: 'O modo solo não tem janela de chat. Com esta opção ligada, a tecla de Alternar chat abre uma linha pequena para falar com NPCs. Comece a linha com ! para gritar.',
281: 'NPCs notam jogadores por perto',
282: 'Pessoas amigáveis e neutras param e olham para você quando você chega perto e fala alguma coisa; amigos de passagem dizem algo; grupos fora da lei confrontam estranhos.',
283: 'Sobreviventes novatos evitam brigas',
284: 'Pessoas comuns assustadas não abrem fogo contra quem não as atacou e recuam quando estão em grande desvantagem. Veteranos e predadores nunca fazem isso.',
285: 'Assaltos',
286: 'Grupos fora da lei podem render um jogador sozinho em vez de atirar: mãos para cima, arma no chão, três ou quatro itens valiosos levados, e depois vão embora. Recuse, e eles atiram.',
287: 'Chance de assalto (porcentagem do normal)',
288: 'Ajusta com que frequência um grupo fora da lei escolhe assaltar em vez de lutar. 100 é o normal, 0 nunca, 200 o dobro de vezes.',
289: 'Canal de rádio do Condado de Knox',
}
