# Sandbox.json PT-BR, entries 290-372.
PT = {
290: 'Uma estação mantida por sobreviventes, com tráfego de rádio da polícia, conversas militares, chamadas de ouvintes, histórias, piadas e boatos sobre o que realmente está acontecendo no seu mundo.',
291: 'Frequência do Rádio do Condado de Knox (kHz)',
292: 'Padrão 99600 = 99,6 MHz. Escolha uma frequência FM livre se a estação de emergência ou outro mod já estiver usando essa. A estação nunca substitui outro canal. Reinicie o servidor depois de mudar isto; abra um rádio para adicionar a predefinição correspondente.',
293: 'Define de uma vez todas as opções de população e frequência deste menu -- 23 delas. Tudo o que você mudar à mão depois é mantido, e os controles abaixo ainda podem MOSTRAR os números antigos mesmo com a predefinição em vigor. O que cada uma significa:\n\nESCASSO - 12 hostis, 2 postos avançados, encontros a cada 8h. Um condado tranquilo.\nBAIXO - 20 hostis, 4 postos avançados, encontros a cada 6h.\nEQUILIBRADO - 32 hostis, 6 postos avançados, encontros a cada 4h. O padrão testado; escolher esta não grava nada e deixa suas edições em paz.\nABUNDANTE - 56 hostis, 9 postos avançados (2 por cidade), encontros a cada 3h, invasões maiores.\nINSANO - 220 hostis, 24 postos avançados, encontros a cada 2h. Um teste de estresse, não um jogo: esta carga nunca foi validada no multijogador.',
294: 'Liga o mod ao mundo que você começou: o Estado desaparece ao longo da primeira semana, e quem você encontra segue o calendário em vez de um sorteio fixo. Recomendado: ligado para um começo normal, desligado se estiver testando.',
295: 'A chave geral. Desligado significa nenhuma pessoa do A-Life -- o mod continua carregado e as ferramentas de admin continuam funcionando. Recomendado: ligado.',
296: 'Ajusta com que frequência você esbarra em alguém. 1,0 é a taxa testada; 2,0 é um condado movimentado, 0,5 um tranquilo. O controle de desempenho mais importante deste menu. Recomendado: 1,0.',
297: 'Ajusta quantas pessoas há em cada grupo. 1,0 mantém os tamanhos definidos -- uma família tem três, uma equipe do exército tem cinco. Acima de 1,5 as lutas ficam longas. Recomendado: 1,0.',
298: 'Até que distância, em quadrados, as pessoas são simuladas por completo. Além disso elas continuam lá e se movendo, só que de forma mais leve. Aumentar isto é o segundo maior custo do menu. Recomendado: 90; baixe para 60 numa máquina fraca.',
299: 'Teto rígido de pessoas hostis vivas ao mesmo tempo. Nada é gerado além disso, independentemente do resto. Recomendado: 32. Uma máquina forte aguenta 48; 80+ é teste de estresse, não um jogo.',
300: 'Chance percentual de um encontro ser sorteado quando chega o intervalo. Recomendado: 25.',
301: 'Horas de jogo entre sorteios de encontro. Menor significa mais frequente. Recomendado: 4.',
302: 'Quadrados de distância mantidos em volta de um abrigo -- nada é gerado ali dentro. Aumente se as pessoas aparecerem perto demais da sua base. Recomendado: 8.',
303: 'As facções lutam entre si, e não só com você. Desligar deixa o condado mais tranquilo e leve, e tira a maior parte do que você veria acontecer de longe. Recomendado: ligado.',
304: 'Quem está perdendo desiste e foge em vez de morrer no lugar. Recomendado: ligado.',
305: 'Grupos podem te parar, te revistar e levar o que você está carregando. Recomendado: ligado.',
306: 'Tiros e gritos são investigados. Desligado deixa as pessoas surdas para tudo que não esteja na linha de visão. Recomendado: ligado.',
307: 'Um grupo disperso se reorganiza em volta do líder em vez de lutar sozinho. Recomendado: ligado.',
308: 'Os grupos viajam juntos em vez de chegarem um de cada vez. Recomendado: ligado.',
309: 'Os corpos largam a arma que carregavam. O estado segue o calendário: na primeira semana é sucata, depois de um mês vale a pena pegar. Recomendado: ligado.',
310: 'Armas podem travar. Recomendado: ligado.',
311: 'Chance percentual por tiro. 1,0 é mais ou menos um travamento a cada carregador e meio. Acima de 5 as lutas viram comédia. Recomendado: 1,0.',
312: 'Com que força as pessoas batem em portas e barricadas, em porcentagem do normal. 200 significa que uma porta trancada não é obstáculo. Recomendado: 100.',
313: 'Um golpe pode acertar mais de um alvo. Recomendado: desligado -- faz as multidões derreterem.',
314: 'As balas atravessam um corpo e atingem o que estiver atrás. Recomendado: desligado, a menos que você queira que o fogo amigo importe muito.',
315: 'Os golpes deixam ferimentos duradouros -- mancar, sangrar, um braço que para de funcionar. Recomendado: ligado.',
316: 'Desenha um rastro visível em cada tiro. Útil para assistir a um tiroteio do qual você não participa; não é realista. Recomendado: desligado.',
317: 'Coloca pessoas nas cidades antes mesmo de você chegar lá, para que um lugar em que você entra já esteja ocupado. EXPERIMENTAL e pesado num começo do zero. Recomendado: desligado no seu primeiro mundo.',
318: 'Quantos lugares podem ser povoados de antemão. Só importa quando a opção acima está ligada. Recomendado: 30.',
319: 'Horas de jogo que uma pessoa é lembrada depois que você sai da área. Ela volta como a mesma pessoa, e não como um novo estranho. 0 esquece na hora. Recomendado: 8.',
320: 'As pessoas revistam corpos e contêineres depois de uma luta em vez de ficarem paradas em cima deles. Recomendado: ligado.',
321: 'Gritos são ouvidos e respondidos. Recomendado: ligado.',
322: 'Os grupos se comunicam entre si -- avisos de contato, alertas, nomes. Recomendado: ligado.',
323: 'As pessoas leem o mundo atrás de sinais seus: um carro estacionado, uma barricada, uma janela acesa. Recomendado: ligado.',
324: 'Um veículo deixado em algum lugar é sinal de que há alguém por perto. Recomendado: ligado.',
325: 'Janelas com tábuas indicam que o lugar está ocupado. Recomendado: ligado.',
326: 'Paredes e pisos que você construiu são reconhecidos como seus. Recomendado: ligado.',
327: 'Um gerador ligado é o sinal mais escandaloso que existe. Recomendado: ligado.',
328: 'Com que força os indícios atraem atenção para a sua base. Acima de 2,0 você será encontrado com frequência. Recomendado: 1,0.',
329: 'Falas em voz. Desligado deixa só o texto. Recomendado: ligado.',
330: 'As pessoas falam -- avisos, exigências, alertas de contato. Recomendado: ligado.',
331: 'Mostra as falas deles na caixa de chat no modo solo, além de em cima da cabeça. Recomendado: ligado.',
332: 'Eles comentam o que conseguem ver de você -- o que você está segurando, se está sangrando. Recomendado: ligado.',
333: 'Eles te avaliam em voz alta antes de decidir. É isso que faz um impasse parecer um impasse. Recomendado: ligado.',
334: 'Grupos podem te render em vez de simplesmente atirar. Recomendado: ligado.',
335: 'Peso percentual de quantas vezes um assalto é escolhido em vez de um ataque. 200 significa que quase sempre tentam roubar primeiro. Recomendado: 100.',
336: 'A transmissão do condado: notícias, boatos, um ou outro idiota com um transmissor. Recomendado: ligado.',
337: 'A frequência para sintonizar o rádio, em kHz. Recomendado: 99600.',
338: 'Os módulos de comportamento como um todo -- cobertura, flanqueio, descanso, coleta e o resto. Desligado deixa as pessoas só andando e atirando, nada mais. Recomendado: ligado.',
339: 'Eles usam cobertura em vez de ficar no aberto. Recomendado: ligado.',
340: 'Um grupo em desvantagem recua em ordem em vez de se espalhar. Recomendado: ligado.',
341: 'Eles fazem curativos em si mesmos e uns nos outros entre as lutas. Recomendado: ligado.',
342: 'Eles podem correr em disparada. Desligado deixa toda perseguição vencível. Recomendado: ligado.',
343: 'Um atirador designado dá fogo de cobertura enquanto os outros se movem. Recomendado: ligado.',
344: 'Eles se movem enquanto atiram em vez de ficarem plantados no lugar. Recomendado: ligado.',
345: 'Cenas à beira da estrada: bloqueios, emboscadas, atiradores no telhado, carros batidos. Recomendado: ligado.',
346: 'Minutos reais entre tentativas de encontro. Menor significa uma estrada mais movimentada. Recomendado: 60.',
347: 'Quantos grupos viajam pelo mapa enquanto você está em outro lugar. Eles são leves -- só custam alguma coisa quando você encontra um. Recomendado: 6; aumente para 12 para um condado lotado.',
348: 'Quantos grupos são gravados no seu save e sobrevivem a um reinício. Recomendado: 3.',
349: 'Quantos esquadrões um único posto avançado pode ter fora em serviço ao mesmo tempo. Recomendado: 1 -- um posto avançado chama reforços quando é atacado, então não precisa de gente parada à toa.',
350: 'Segundos entre atualizações do mundo offline. Mais alto é mais leve e menos preciso. Recomendado: 20.',
351: 'Com que rapidez os grupos atravessam o mapa quando você não está olhando. 150 é um ritmo de caminhada com paradas. Recomendado: 150.',
352: 'Um grupo que perdeu gente para você volta atrás de você, dias depois, no lugar onde você foi visto por último. Recomendado: ligado.',
353: 'As facções constroem e mantêm lugares de verdade -- guarnições, patrulhas, vigias, um rádio. Recomendado: ligado.',
354: 'Quantos postos avançados existem ao mesmo tempo. Cada um é uma população fixa, então isso tem um custo real. Recomendado: 6; 10 ou mais pede uma máquina forte.',
355: 'Quantos postos avançados podem ficar em volta de uma cidade. Recomendado: 1.',
356: 'Quantos postos avançados podem ficar no interior, longe das cidades. Recomendado: 2.',
357: 'Minutos reais entre tentativas de criar um novo posto avançado. Recomendado: 30.',
358: 'Chance percentual de uma tentativa dar certo. Recomendado: 20.',
359: 'A que distância de você, em quadrados, um posto avançado pode ser construído. Pequena demais e você vê um aparecer. Recomendado: 120.',
360: 'A que distância você precisa estar, em quadrados, para um posto avançado colocar sua guarnição no mundo. Recomendado: 90.',
361: 'Os grupos podem pedir ajuda -- um carro encostando, ou um helicóptero descendo gente por cordas. Recomendado: ligado.',
362: 'O que as pessoas fazem depois que escurece. Lanternas é a opção mais legível; Oculto deixa as noites realmente perigosas. Recomendado: Lanternas.',
363: 'Quanto acontece durante a noite, no geral. Recomendado: Moderada.',
364: 'As patrulhas param, sentam e descansam em vez de andar para sempre. Recomendado: ligado.',
365: 'Descanso mais curto, em minutos de jogo. Recomendado: 20.',
366: 'Descanso mais longo, em minutos de jogo. Recomendado: 45.',
367: 'Horas de jogo caminhando antes de uma patrulha querer descansar. Recomendado: 3,0.',
368: 'Como o mundo é lido para o posicionamento -- quais cidades e estradas contam. Recomendado: deixe como a predefinição definiu.',
369: 'Com que frequência acontecem cenas à beira da estrada. Recomendado: Normal.',
370: 'Com que frequência aparecem grupos viajantes. Recomendado: Normal.',
371: 'Com que frequência aparecem sobreviventes solitários. Recomendado: Normal.',
372: 'Com que frequência acontecem eventos distantes -- tiros atrás do morro, um helicóptero, uma batida. São só atmosfera e quase não custam nada. Recomendado: Normal.',
}
